### ISSUE TITLE
Error when running ./install.sh -a 

### ISSUE THREAD

**Issue by hugozidos** [mininet/mininet#1014]
Traceback (most recent call last):
  File "get-pip.py", line 24226, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpCz4C9p/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

this was gotten when installing on ubuntu 20.0.4

**Comment by lantz** [comment]
So obviously get-pip is the python3 version and is being executed with python2.  It used to work as of last week.

However, I can't reproduce this, because python-pip-whl is installed.

Can you please try:

    $ sudo apt install python-pip-whl

and can you also try


    $ bash -x mininet/util/install.sh -n

and include the output? thanks

**Comment by lantz** [comment]
Incidentally, `install.sh` is tested on Ubuntu 20.04 in the CI builds.

see: https://github.com/mininet/mininet/actions?query=workflow%3Amininet-tests

**Comment by lantz** [comment]
Well this is amazingly annoying. It looks like you can no longer easily install `pip` for python 2 on ubuntu.

**Comment by lantz** [comment]
Seen in CI build https://github.com/mininet/vm-build/runs/1755683116?check_suite_focus=true
