### ISSUE TITLE
[Need help] Using X11 tunnel with Macos Big Sur and XQuartz 2.8.0

### ISSUE THREAD

**Issue by lorenzomonta** [mininet/mininet#1048]
Hello,

To connect to mininet vm I'm running the ssh command : `ssh -X mininet@192.168.56.101`
when I'm in, If for example I run `sudo xterm` or `sudo wireshark` I see access denied: 
```
mininet@mininet-vm:~$ sudo xterm
X11 connection rejected because of wrong authentication.
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
```
But if i run only `xterm` or `wireshark`, it works, but without sudo privilege.
So every time I log out and then log in, I have to run the following commands to make it work temporarily:
```
mininet@mininet-vm:~$ xauth list
mininet-vm/unix:10  MIT-MAGIC-COOKIE-1  2a909a6567f468b2330b6f3f2c828848
mininet@mininet-vm:~$ sudo xauth list
mininet-vm/unix:10  MIT-MAGIC-COOKIE-1  e8c10acb47f791818c535ed974484cc5
mininet@mininet-vm:~$ sudo xauth remove mininet-vm/unix:10
mininet@mininet-vm:~$ sudo xauth add mininet-vm/unix:10  MIT-MAGIC-COOKIE-1  2a909a6567f468b2330b6f3f2c828848
mininet@mininet-vm:~$ sudo xauth list
mininet-vm/unix:10  MIT-MAGIC-COOKIE-1  2a909a6567f468b2330b6f3f2c828848
```

What can I do to fix this problem permanently?
Thank you

**Comment by lantz** [comment]
Please don't abuse github actions with requests for help. :(

Also please read the FAQ and walkthrough.

**Comment by lorenzomonta** [comment]
I've been going crazy for a week! Please help me solve this issue and I won't write anymore! please
I have read the FAQ over and over again but there is no solution.

**Comment by lantz** [comment]
[FAQ](https://github.com/mininet/mininet/wiki/FAQ#x11-forwarding)
[Walkthrough](http://mininet.org/walkthrough/#start-wireshark)

**Comment by lorenzomonta** [comment]
> https://github.com/mininet/mininet/wiki/FAQ#x11-forwarding
> http://mininet.org/walkthrough/#start-wireshark

You are right! I'm sorry! I didn't read it right!
Thank you for your reply!

Have a nice evening!
