### ISSUE TITLE
Error when save files in miniedit

### ISSUE THREAD

**Issue by Vihanmy** [mininet/mininet#1054]
Big sur(M1)>Parallels>Ubuntu 20.10>Python3.8
Error occurs when i save my topo in miniedit.

alex@vu:~/Desktop/SDN/mininet/examples$ ./miniedit.py
topo=none 
a bytes-like object is required, not 'str'

**Comment by lantz** [comment]
Please don't ignore the issue template.

Could you please try the following:

1. Provide detailed instructions on how to reproduce the issue
2. Confirm that the same procedure reproduces the issue in of our Mininet VM images
3. Confirm that this is a different issue from #1049 

Thanks.
