### ISSUE TITLE
Packet loss and link delay between two hosts in single switch network

### ISSUE THREAD

**Issue by ryankshah** [mininet/mininet#1055]
So for a part of my phd thesis I am doing a paper involving the mininet sdn. I am curious as some of my experiments involve using packet loss and link delay over a link between two hosts. First, what is the algorithms used for packet loss and link delay? Are they random? I.e. are they uniformly-at-random? Second, is mininet a state-of-the-art in simulating jitter (packet loss) and link delay?

### Expected/Desired Behavior:

It would be great to see if we can specify our own packet loss and delay algorithms if the state of the art. The documentation does not really explain these parameters.

Currently in the source code (https://github.com/mininet/mininet/blob/master/mininet/test/test_hifi.py) it states that drops are probabilistic but what is the element of randomness used in this model?

### Actual Behavior:

I am assuming the packet loss and delay are uniformly at random. Can this be specified? Thanks!

**Comment by lantz** [comment]
Hy @ryankshah I appreciate that you are using Mininet but please a) do not abuse github issues for non-bugs b) you will probably want to consult our papers and also look into the underlying subsystems (and their documentation and code)
