### ISSUE TITLE
Tor Network Inside MiniNet

### ISSUE THREAD

**Issue by cheznewa** [mininet/mininet#1058]
Is Possible To Add Tor Network Inside Mininet In example Folder Or Feature, with desired number of ::: relay, exit, web, hidden-service, client, diractory authroity; do create config file and run tor path.

**Comment by lantz** [comment]
Is the issue template not showing up? It's supposed to say:

> **Mininet uses GitHub issues for bug reports and feature requests only.**
These issues can be viewed at bugs.mininet.org
>
> If you have a question that is not a **bug report** or a **feature request**,
> please use the documentation at docs.mininet.org, the FAQ
> at faq.mininet.org, and the mininet-discuss mailing list.
