### ISSUE TITLE
h1 -> *** Error: could not parse ping output: PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.

### ISSUE THREAD

**Issue by whisperLiang** [mininet/mininet#1063]
**Mininet uses GitHub issues for bug reports and feature requests only.**
These issues can be viewed at bugs.mininet.org

If you have a question that is not a **bug report** or a **feature request**,
please use the documentation at docs.mininet.org, the FAQ
at faq.mininet.org, and the mininet-discuss mailing list.

For bug reports, please fill in the following information in detail,
and also feel free to include additional information such as debug
output from mn -v debug, etc.
--- Cut Here ---

**Comment by whisperLiang** [comment]
mininet> pingall
*** Ping: testing ping reachability
h1 -> *** Error: could not parse ping output: PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
64 比特，来自 10.0.0.2: icmp_seq=1 ttl=64 时间=1.07 毫秒

--- 10.0.0.2 ping 统计 ---
已发送 1 个包， 已接收 1 个包, 0% 包丢失, 耗时 0 毫秒
rtt min/avg/max/mdev = 1.067/1.067/1.067/0.000 ms

X 
h2 -> *** Error: could not parse ping output: PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
64 比特，来自 10.0.0.1: icmp_seq=1 ttl=64 时间=1.19 毫秒

--- 10.0.0.1 ping 统计 ---
已发送 1 个包， 已接收 1 个包, 0% 包丢失, 耗时 0 毫秒
rtt min/avg/max/mdev = 1.191/1.191/1.191/0.000 ms

X 
*** Results: 100% dropped (0/2 received)

**Comment by whisperLiang** [comment]
Is the mininet normal?

**Comment by santiagorr** [comment]
I've been hit by this also on an ubuntu 20.04 machine.

```
$ sudo mn
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller
c0 
*** Starting 1 switches
s1 ...
*** Starting CLI:
mininet> pingall
*** Ping: testing ping reachability
h1 -> *** Error: could not parse ping output: PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
64 octets de 10.0.0.2 : icmp_seq=1 ttl=64 temps=3.41 ms

--- statistiques ping 10.0.0.2 ---
1 paquets transmis, 1 reçus, 0 % paquets perdus, temps 0 ms
rtt min/avg/max/mdev = 3.405/3.405/3.405/0.000 ms

X 
h2 -> *** Error: could not parse ping output: PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
64 octets de 10.0.0.1 : icmp_seq=1 ttl=64 temps=2.21 ms

--- statistiques ping 10.0.0.1 ---
1 paquets transmis, 1 reçus, 0 % paquets perdus, temps 0 ms
rtt min/avg/max/mdev = 2.211/2.211/2.211/0.000 ms

X 
*** Results: 100% dropped (0/2 received)
mininet> 
```
Please note the pings do get a response.

I get the same result with mininet 2.2.2 and 2.3.0. The latter manually installed with the ubuntu impish .deb:
[https://launchpad.net/ubuntu/impish/amd64/mininet/2.3.0-1ubuntu1](https://launchpad.net/ubuntu/impish/amd64/mininet/2.3.0-1ubuntu1)

**Comment by santiagorr** [comment]
So the problem is due to the localized strings of the ping output. This works on the same machine:
```
$ LANG=C sudo mn
[sudo] password for user: 
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller
c0 
*** Starting 1 switches
s1 ...
*** Starting CLI:
mininet> pingall
*** Ping: testing ping reachability
h1 -> h2 
h2 -> h1 
*** Results: 0% dropped (2/2 received)
```
