### ISSUE TITLE
Problems with TCP connection + loss

### ISSUE THREAD

**Issue by Alex87a** [mininet/mininet#1070]
Hi, I find myself using this tool of yours on a virtual machine with Ubuntu 20.04 installed.  Since I was assigned the task of creating a topology with four hosts (h1 h2 h3 h4) where between h1-h3 there is a TCP connection while between h2-h4 a UDP connection.  Between the central switches (s1 s2) there is a rate equal to 2 Mb, delay 10ms and Loss equal to 0% initially and then pass to 50%.  However, although everything works fine at first and outputs the corresponding throughput, when I switch to the connection with 50% Loss, the TCP traffic generates me Throughput equal to 0. How can I do to solve?

**Comment by janev94** [comment]
@Alex87a how are you modifying the loss rate dynamically? Do you have a code example?

**Comment by lantz** [comment]
This seems more like a question "why doesn't TCP work with 50% packet loss?"
Closing.
