### ISSUE TITLE
Accessing to a database in mininet from one host to another

### ISSUE THREAD

**Issue by p4pifor** [mininet/mininet#1083]
Hi,
I'd like to access to a database(mariadb) running in one host from another one. The database is configured as follows: https://linuxhint.com/expose_mysql_server_internet/ in order to make it externally accessible. However, when running `mysql -u MY_USER -h HOST_IP_ADDR -p` it ends in failure.

`ERROR 2003 (HY000): Can't connect to MySQL server on ´HOST_IP_ADDR´ (111 "Connection refused")`

Moreover, `lsof -i` command gives me no answer, afaik, it should at least display mysql port (3306) since the database works when accessing it from the host where it is running. Does anyone know what may be happening? My firewall is disabled. Any help will be really appreciated, thanks in advance :)

**Comment by cheriimoya** [comment]
how did you start the mysql server? or better, did you start it?

**Comment by lantz** [comment]
This looks like a mysql configuration (and possibly shared fs) issue, rather than a mininet issue.
@cheriimoya 's comment is appropriate, but please follow up on the mailing list for user questions that aren't mininet bugs.
