### ISSUE TITLE
iperf3 TCP testing with ingress policing between hosts

### ISSUE THREAD

**Issue by joe820912boy** [mininet/mininet#1084]
when I test the ingress policing with TCP protocol that I found problem with it

my testing topology is very simple, ex. h1--s1--h2
here is my setting about ingress policing
![ingress](https://user-images.githubusercontent.com/12133662/126942572-af3b029d-ebb2-4991-a284-97ffdb62ef0b.JPG)

then when I run the iperf3 and test with TCP
I found that the h2 received is not match '15Mbps', it was smaller than it.
but if I used UDP protocol to test, and h2 received very close '15Mbps' or you could say 'equal'
Does ingress policing not support TCP protocol?

Can any one help to solve this problem? Or did you face the same question before?

**Comment by joe820912boy** [comment]
I find the solution in ovs-vswitchd.conf.db.5, and link it here[http://www.openvswitch.org//ovs-vswitchd.conf.db.5.pdf](url); it's openvswitch official documentation.

Policing interacts badly with some network protocols, and especially with fragmented IP packets.

So I add an additional 'virtual' switch before entering network and a exgress queue to make it like 'policing ingress' 

The result match what I want for TCP and UDP protocol

**Comment by janev94** [comment]
@lantz OP provided the solution, still this seems to be a ovs related question and not a mininet bug/feature request. Consider closing this.

**Comment by lantz** [comment]
Closing due to workaround and to core issue being with OvS.
