### ISSUE TITLE
Change MTU (Maximum Transmission Unit) of a mininet host

### ISSUE THREAD

**Issue by p4pifor** [mininet/mininet#1087]
How can I change the MTU of a mininet host through the python script? I've figured it out with my switch's interfaces, I'm not able to do it with hosts though. Any idea of how can I do it? Thanks in advance

**Comment by shamimtowhid** [comment]
Hello,
I am not sure whether this is the correct way to do this or not, but
I found a workaround for this. 

When creating topology using python script we can run commands inside every host. Using the "ifconfig" command we can change MTU of a mininet host. 

Example Code:

 h1.cmd('ifconfig h1-eth0 mtu 65535') # here h1-eth0 is the interface name, 65535 is the new MTU for host 1.

NOTE: the above command must be executed before starting the CLI inside the python script.

**Comment by lantz** [comment]
Remember not to abuse github issues by posting support requests or usage questions.
