### ISSUE TITLE
can't start x server:  `qt.qpa.xcb: X server does not support XInput 2`

### ISSUE THREAD

**Issue by heavenkiller2018** [mininet/mininet#1088]
**Mininet uses GitHub issues for bug reports and feature requests only.**
These issues can be viewed at bugs.mininet.org

If you have a question that is not a **bug report** or a **feature request**,
please use the documentation at docs.mininet.org, the FAQ
at faq.mininet.org, and the mininet-discuss mailing list.

For bug reports, please fill in the following information in detail,
and also feel free to include additional information such as debug
output from mn -v debug, etc.
--- Cut Here ---
### Detailed Steps to Reproduce the Behavior:

when I want to use x server ,the following error was showed:

```bash
mininet@mininet-vm:~$ sudo wireshark &
[1] 1719
mininet@mininet-vm:~$ qt.qpa.xcb: X server does not support XInput 2
failed to get the current screen resources
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 0 (Success) on X server "localhost:10.0"
      after 291 requests (286 known processed) with 0 events remaining
```

how to fix this error?and what's is its origin?

**Comment by heavenkiller2018** [comment]
I tested 'xclock' and 'xterm',  both of them can function very well, so my configuration of X11 should be all right.

**Comment by ysy0722** [comment]
If you have solved it, could you tell me the solution?

**Comment by lantz** [comment]
This seems to work fine using the Mininet VM image, so I am closing this.

You haven't provided a lot of information, but on Ubuntu I've had better luck with `wireshark-gtk` rather than `wireshark-qt` due to Qt's apparent contempt for X11 compatibility.
