### ISSUE TITLE
Proposed addition to webpage tutorial

### ISSUE THREAD

**Issue by Cogit8or** [mininet/mininet#1093]
Proposed addition to the mininet tutorial at [http://mininet.org/vm-setup-notes/](url)
To be placed between steps 3 and 4 under the VirtualBox subheading (but not as an additional numbered step, I don't think): 

If starting the VM gives an error which mentions "64-bit CPU," it is possible that virtualization needs to be enabled in your computer's BIOS settings. This takes only seconds, but requires a computer restart to access the BIOS. Which key to press during startup to access your BIOS, as well as the name of the setting which controls virtualization, varies by motherboard (e.g. 'SVM Mode'), but should be easy to look up provided you know what brand of motherboard you have. Some BIOS interfaces also have search features to make finding specific settings painless.

**Comment by lantz** [comment]
This is from my colleague actually; moved to https://github.com/mininet/mininet.github.com/issues/17
