### ISSUE TITLE
Unable to save and open topology and level 2 script in MiniEdit.

### ISSUE THREAD

**Issue by Virakwan** [mininet/mininet#1097]
I used "Mininet 2.3.0" with VM files "mininet-2.3.0-210211-ubuntu-20.04.1-legacy-server-amd64-ovf.zip" latest release. I run it in Virtualbox platform. I faced a problem when I run Miniedit and save the .mn files. The .mn file that I saved is empty when open. Any solution can I fix this problem?

**Comment by cheriimoya** [comment]
isn't this the exact same issue as #1086 ? i think this can be closed in that case @lantz

**Comment by lantz** [comment]
closed as dup of #1086
