### ISSUE TITLE
Help with the project

### ISSUE THREAD

**Issue by cheriimoya** [mininet/mininet#1099]
This is not a feature request, nor a bug report, i simply want to _somehow_ help the project in the coming two months.

Initially, i read the FAQ and the Support sites on mininet.org.
They told me to write to the mailing list, which i did:

```
Hi there,

i am a studying at the University of Stuttgart and as part of a lecture, 
I'd like to help the Mininet project.
Is this the correct place to ask for some issues to help with or should 
this rather go on the GitHub issue tracker?

Cheers,
```

The reply was

```
Hello,

here there are sometimes user questions, but no questions about the project
and its issues itself. So to help the project you may be better off on
github.

Best regards
```

so i guess i am asking here for something to help the project with.
I looked at issues with the 'good first issue' label, but there were none.

I looked at how the mininet vm is being generated and it looks like there is some improvement potential.
Could vagrant be an alternative here?

Does anybody have some other ideas about things i can help with that are not too big?

**Comment by cheriimoya** [comment]
ah, right @lantz 

maybe you have the watch filter "mentions and participating only".

the reason why you might have many emails for old issues and/or PRs is this issue;)

**Comment by lantz** [comment]
Normally I'd close this since it's not technically an issue, but resolving issues and PRs is actually really helpful.
I'll try to smash through some of your queue this week.
There are all kinds of things that can and should be improved, certainly, including some breakages on current debian/ubuntu.

**Comment by cheriimoya** [comment]
Project is over, I'll stay around at least as long my issues/prs are closed in any way (merged/closed).
