### ISSUE TITLE
mininet protocol error

### ISSUE THREAD

**Issue by JackMote** [mininet/mininet#1101]
`witchd.service - Open vSwitch Forwarding Unit
     Loaded: loaded (/lib/systemd/system/ovs-vswitchd.service; static; vendor preset: enabled)
     Active: active (running) since Wed 2022-01-12 16:09:48 CST; 1min 31s ago
    Process: 2076 ExecStart=/usr/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server --no-monitor --system-id=random -
   Main PID: 2114 (ovs-vswitchd)
      Tasks: 1 (limit: 4303)
     Memory: 2.6M
     CGroup: /system.slice/ovs-vswitchd.service
             └─2114 ovs-vswitchd unix:/var/run/openvswitch/db.sock -vconsole:emer -vsyslog:err -vfile:info --mlockall

Jan 12 16:09:51 SIG-0107 ovs-vswitchd[2114]: ovs|00008|netlink_socket|ERR|transaction error (Protocol error)
Jan 12 16:09:51 SIG-0107 ovs-vswitchd[2114]: ovs|00010|ofproto_dpif|ERR|failed to open datapath of type system: Protoc
Jan 12 16:09:51 SIG-0107 ovs-vswitchd[2114]: ovs|00011|ofproto|ERR|failed to open datapath s1: Protocol error
Jan 12 16:09:51 SIG-0107 ovs-vswitchd[2114]: ovs|00012|bridge|ERR|failed to create bridge s1: Protocol error
Jan 12 16:09:51 SIG-0107 ovs-vswitchd[2114]: ovs|00013|netlink_socket|ERR|received invalid nlmsg (120 bytes < 16)
Jan 12 16:09:51 SIG-0107 ovs-vswitchd[2114]: ovs|00015|netlink_socket|ERR|received invalid nlmsg (120 bytes < 16)
Jan 12 16:09:51 SIG-0107 ovs-vswitchd[2114]: ovs|00016|netlink_socket|ERR|transaction error (Protocol error)
Jan 12 16:09:51 SIG-0107 ovs-vswitchd[2114]: ovs|00018|ofproto_dpif|ERR|failed to open datapath of type system: Protoc
Jan 12 16:09:51 SIG-0107 ovs-vswitchd[2114]: ovs|00019|ofproto|ERR|failed to open datapath s1: Protocol error
Jan 12 16:09:51 SIG-0107 ovs-vswitchd[2114]: ovs|00020|bridge|ERR|failed to create bridge s1: Protocol error
![微信图片_20220112161636](https://user-images.githubusercontent.com/96284389/149089473-5f9dc29b-5ee4-4b3f-8d7b-77de4e930d5d.png)
![微信图片_20220112161935](https://user-images.githubusercontent.com/96284389/149089912-01510a25-a504-4870-b4fc-dc217e09e3f3.png)
Please how to solve this problem？
`

**Comment by janev94** [comment]
@JackMote what is the problem? How did you install mininet/openvswitch? Have you tried issuing a cleanup `mn -c `or re-installing the libraries? Seems like a ovs issue and not mininet @lantz consider closing this issue.

**Comment by lantz** [comment]
This is not an issue with the Mininet VMs or standard installation and kernels. Closing.
