### ISSUE TITLE
Mininet File not opening 

### ISSUE THREAD

**Issue by rajiaji** [mininet/mininet#1115]
![Error](https://user-images.githubusercontent.com/75720957/155835875-1e9925b6-8ae6-4b90-b0e4-d4986750866b.jpg)

I was downloading [mininet-2.3.0-210211-ubuntu-16.04.6-server-i386-ovf.zip] for windows host.
This file was unable to open and run. Please advice to solve the issue . Screenshot attached

**Comment by janev94** [comment]
@rajiaji to open this file you need some virtualization software (VirtualBox, VMWare workstation, libvirt, etc). The archive contains a pre-packaged virtual machine, but you should be able to install mininet natively or within any virtualization environment that you want.

@lantz consider closing this.
