### ISSUE TITLE
Large Overhead for traffic monitory

### ISSUE THREAD

**Issue by skyerguo** [mininet/mininet#1116]
**Mininet uses GitHub issues for bug reports and feature requests only.**
These issues can be viewed at bugs.mininet.org

If you have a question that is not a **bug report** or a **feature request**,
please use the documentation at docs.mininet.org, the FAQ
at faq.mininet.org, and the mininet-discuss mailing list.

For bug reports, please fill in the following information in detail,
and also feel free to include additional information such as debug
output from mn -v debug, etc.
--- Cut Here ---
### Expected/Desired Behavior:

Get real-time network traffic information in text format using popular tools.

### Actual Behavior:

Large CPU overhead in mininet.

### Detailed Steps to Reproduce the Behavior:

First build a mininet topology. Then use "iftop" to monitor the network traffic in any host.
Then, use htop or top monitor the CPU usage. It can be seen that the overhead is seemly very huge. 

### Additional Information:
One iftop monitor one host, will make full use of a core of CPU.
Tool "iptraf" has the same problem.

**Comment by janev94** [comment]
@skyerguo is the CPU overhead coming from mininet or is it coming from iftop, iptraf etc? What is your specific use-case and why do you need these? Do you need live monitoring or can you not record the packet information using pcap and analyze it later?

**Comment by lantz** [comment]
This doesn't seem to be a mininet issue. I was also unable to reproduce it in my VM.

 If you think there is a specific Mininet issue we can reopen it, but I don't think there is.
