### ISSUE TITLE
New version release with working installation script

### ISSUE THREAD

**Issue by jadinm** [mininet/mininet#1120]
Could we have a new release of mininet including the commit c3ba039a9781c6c5f475b7c88ff577185747a1da ?

Otherwise, we have to either tag explicitly the commit hash (or the master branch) or cherry pick the commit to get a working installation script

**Comment by Telluur** [comment]
For those that need it now, I've forked the repo and created a release including the cherrypicked https://github.com/mininet/mininet/commit/c3ba039a9781c6c5f475b7c88ff577185747a1da commit.

See; https://github.com/Telluur/mininet/releases/tag/2.3.0sec

**Comment by lantz** [comment]
Is this necessary since #1100 was merged on February 23rd?

**Comment by jadinm** [comment]
It is necessary to fix mininet version if I want to be certain of the behavior of my library that runs on top of mininet.

Otherwise, depending on the time of installation of the other library, I will have a different behavior.

And, it is cleaner to fix it with a real tag than with a commit hash.

**Comment by Telluur** [comment]
I think this issue can be closed, as it was fixed in #1124 with tag [2.3.1b1](https://github.com/mininet/mininet/releases/tag/2.3.1b1) (https://github.com/mininet/mininet/commit/aa0176fce6fb718a03474f8719261b07b670d30d).

Thanks.

**Comment by lantz** [comment]
Closed by #1124.
