### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by Enchufa2** [mininet/mininet#1121]
I intend to package mininet in the official Fedora repos, but the current non-standard license text may be a blocker. Our [packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/) require us to set a license identifier from a [list of approved licenses](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#SoftwareLicenses). mininet's license is identified as BSD in the `setup.py` file, but then the text is not standard and it is more similar to a MIT license (automatic tools identify it as MIT, in fact). Would you consider switching to a standard text, such as the 3-Clause BSD license?

**Comment by lantz** [comment]
Personally I'm fine with changing the license but it's somewhat tricky because it requires approval from ONF (probably not hard) and Stanford (harder!)

It's basically a BSD 3-clause license but the text is the OpenFlow license from Stanford, which Debian and Ubuntu (at least) were OK with.

**Comment by Enchufa2** [comment]
Please see [this](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/WVP4IVDG53PY3GBZTZBVPZ6LSHHJZFMN/) for an ongoing discussion about this license.

**Comment by Enchufa2** [comment]
Unfortunately, [this is the final decision](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/message/SKULHAVWI44Z7PDFXIV7XGAST2UCSMLQ/):

> Unfortunately we have decided this license does not meet Fedora's
> minimum standards for a free software/open source license.
> 
> The license may continue to be tolerated for software that is
> currently packaged in Fedora, but would not be allowed for future
> packages.
>
> My recommendation would be to try to get the upstream developers to
> switch to an OSI-approved permissive license like the MIT license.

So I'd love to package this for Fedora, but my hands are tied, sorry. Please feel free to close this as wontfix or to ping me if you finally manage to change the license.

**Comment by lantz** [comment]
@Enchufa2  Actually managed to get the approvals (in addition to my own) with help from folks at ONF and Stanford.

Merged in #1141 

Github now auto-detects it as a BSD 3-clause license.

**Comment by Enchufa2** [comment]
That's great, thank you! The package got approved before being locked by legal, so I'll just continue with the process and bring it into Fedora. :)

**Comment by Enchufa2** [comment]
BTW, could you please also release a new minor version? Otherwise, I could just package the specific commit for now, but it would be easier for me if you tag a minor release.

**Comment by Enchufa2** [comment]
Here we go: https://src.fedoraproject.org/rpms/mininet. Built for:

- F36: https://bodhi.fedoraproject.org/updates/FEDORA-2022-2e05a45d4e
- F37: https://bodhi.fedoraproject.org/updates/FEDORA-2022-b770d5b048

**Comment by janev94** [comment]
@lantz this seems to have been resolved. Fedora builds are available as Enchufa2 quoted in their last comment.
