### ISSUE TITLE
ERROR when too much hosts link with a switch

### ISSUE THREAD

**Issue by skyerguo** [mininet/mininet#1122]
**Mininet uses GitHub issues for bug reports and feature requests only.**
These issues can be viewed at bugs.mininet.org

If you have a question that is not a **bug report** or a **feature request**,
please use the documentation at docs.mininet.org, the FAQ
at faq.mininet.org, and the mininet-discuss mailing list.

For bug reports, please fill in the following information in detail,
and also feel free to include additional information such as debug
output from mn -v debug, etc.
--- Cut Here ---
### Expected/Desired Behavior:

I want to use a switch to connect with many hosts. However, when the number of hosts is larger than 50, it will result in some error.

### Actual Behavior:

The error is that, after net.addLink with more than 50 hosts(for example 60) to a single switch(assume it is named as sw10), using "ifconfig -a", I can see sw10-eth1, sw10-eth2...,sw10-eth60, but except the "sw10" itself. If the hosts number is smaller(for example 40), using "ifconfig -a" it will show sw10-eth1, sw10-eth2...,sw10-eth40, and sw10.

### Detailed Steps to Reproduce the Behavior:

Using net.addLink in python to add many hosts (40 and 60, respectively) to a switch(assume it is named as sw10).
And in CLI input "sh ifconfig -a" or add a new terminal to input "ifconfig -a", it will show the difference. "sw10" will only appear in 40 hosts.

### Additional Information:

It is really a bug. If you cannot recurrent this, do not hesitate to contact with me, I can give you the example code.

**Comment by lantz** [comment]
This works fine in my setup: `sudo mn --switch single,100 --test ping`

**Comment by lantz** [comment]
Closing for now. If this still seem to be a problem we can reopen it.
