### ISSUE TITLE
unknown device type

### ISSUE THREAD

**Issue by Vesper0704** [mininet/mininet#1126]
### Expected/Desired Behavior:
sudo mn --nat  can create the demo.
### Actual Behavior:
error creating interface pair unknown device type
### Detailed Steps to Reproduce the Behavior:
sudo mn --nat
### Additional Information:
mininet 2.2.2

**Comment by lantz** [comment]
Can you confirm that this behavior occurs in a current Mininet VM using Mininet 2.3.0?

**Comment by janev94** [comment]
Issue is not present in mininet 2.3.0

**Comment by lantz** [comment]
Closing as fixed/not reproducible in current mininet.
