### ISSUE TITLE
dynamic change link feature on runtime

### ISSUE THREAD

**Issue by Lu-Yi-Hsun** [mininet/mininet#1127]
for example start mininet
net.addLink(s1, s2,port1=888,port2=321,cls=TCLink, bw=1000,jitter="450ms",delay="0.75s",loss=11,max_queue_size=23)

how can i change the link   delay from 0.75->1 on runtime

**Comment by lantz** [comment]
If you have a question that is not a **bug report** or a **feature request**,
please use the documentation at docs.mininet.org, the FAQ
at faq.mininet.org, and the mininet-discuss mailing list.
