### ISSUE TITLE
No module named mininet

### ISSUE THREAD

**Issue by AlexavierCarlen** [mininet/mininet#1128]
I did successfully install mininet and ryu and both worked well in basic. However, for another project, when I execute the .py code for mininet, there is always the error " No module named: 'mininet' ". But I found that all other projects on github have the same lines:
"from mininet.#$% import Mininet,etc". Even the teaching mentioned this.
I coudn't find any solutions to this problem, hope somebodies will be able to help.
![image](https://user-images.githubusercontent.com/48858924/163751211-422340e6-73bd-4edb-8733-e23b1b3abb7c.png)
![image](https://user-images.githubusercontent.com/48858924/163751215-fad16993-e857-40d2-a9cf-6af8baaeea56.png)

**Comment by timskovjacobsen** [comment]
Your prompt indicates that you have a virtual environment activated. You likely installed `mininet` inside the virtual environment.
However, `python3` refers to the globally installed Python instance. Try to type `python topo.py` instead.

The above works for Linux, which I assume you are using. The shell looks like the default theme for the Gnome shell.

**Comment by janev94** [comment]
@lantz the issue seems to be that the OP has not installed mininet for the python interpreter that they tried to use. I think it is ok to close this. @AlexavierCarlen please confirm

**Comment by lantz** [comment]
This appears to be a python environment/path issue. If you think it isn't we can reopen it.
