### ISSUE TITLE
Tensorflow in Mininet

### ISSUE THREAD

**Issue by SilvaEngComp** [mininet/mininet#1131]
### Expected/Desired Behavior:
tensorflow to be available to use
### Actual Behavior:
Tensorflow is installed but not available in mininet xterm
### Detailed Steps to Reproduce the Behavior:
install ubuntu 20.04
install python3 and pip3
install tensorflow
start mininet
run xterm h1
run pip list or pip freeze

### Additional Information:
All others libs are available, only tensorflow is not.

**Comment by lantz** [comment]
Tensorflow - or problems with your python configuration - have nothing to do with Mininet.
Also you seem to be confusing pip and pip3.
