### ISSUE TITLE
ping doesn't work with xterm in mininet 2.3.0

### ISSUE THREAD

**Issue by drphamwit** [mininet/mininet#1135]
### Expected/Desired Behavior:
h1 can ping h2 when running the command ping h2 in h1 xterm terminal
### Actual Behavior:
root@mininet-vm:~# ping h2
ping: h2: Temporary failure in name resolution

### Detailed Steps to Reproduce the Behavior:
1. sudo mn
2. xterm h1 h2
3. On h1 xterm terminal, try ping h2
4. Error message: ping: h2: Temporary failure in name resolution

### Additional Information:
This ping works in an older version of mininet. Tried to look for a solution in GitHub issues for 2.3.0 but cannot find anything. Not sure if anyone had this issue before.

**Comment by lantz** [comment]
Closing since the `h1...` aliases are a feature of the Mininet CLI. Custom host entries may be added to DNS or to `/etc/hosts` (possibly a private version of the latter using custom directories.)
