### ISSUE TITLE
sudo make install PYTHON=python3 

### ISSUE THREAD

**Issue by brucecui1998** [mininet/mininet#1149]
I am a novice in the installation of mininet，when I run the command "sudo make install PYTHON=python3 ".I got this.
![图片](https://user-images.githubusercontent.com/70733628/197426002-3100cdf1-2d74-4c7c-b70b-2d81c9d66671.png)
Anybody can help me?

**Comment by lantz** [comment]
I can't reproduce this on Ubuntu 20.04 with Mininet 2.3.1b1.

If this is still an issue, please reopen it and include complete and detailed instructions for reproducing the issue.
