### ISSUE TITLE
AttributeError examples/miniedit.py line 1423

### ISSUE THREAD

**Issue by GregHoff** [mininet/mininet#1186]
Using the mininet version-
commit 8725056d7bfc8939a535c7d2f53c53e1924f732b (HEAD -> master, origin/master, origin/HEAD)
Author: lantz <rlantz@cs.stanford.edu>
Date:   Tue May 2 19:12:33 2023 -0700

A change was made to examples/miniedit.py in this previous [commit](https://github.com/mininet/mininet/commit/cf5675876c163f39706b1fb0d0e4ab706260af1b#diff-4b883492fdd7f99699186e4219deed028dec0da46cd051b08bc7e68489c32152R1420) that is causing a runtime error

### Expected/Desired Behavior:
1. run examples/miniedit.py from a terminal window
2. in the MiniEdit window, click the menu option File -> Open
3. select a Mininet Topology file
4. click the Open button
5. the previously saved topology is displayed in the window and ready to run

### Actual Behavior:
5. After clicking the Open button, the Open window closes
6. focus is returned to the MiniEdit window
7. the primary pane of the MiniEdit window remains blank
8. the following message is displayed in the terminal window

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/user/mininet/examples/miniedit.py", line 1445, in loadTopology
    loadedTopology = self.convertJsonUnicode(json.load(f))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mininet/examples/miniedit.py", line 1423, in convertJsonUnicode
    unicode = globals.get( 'unicode', str )
              ^^^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'get'
```

### Additional Information:
On line 1423 in examples/miniedit.py, instead of 
`unicode = globals.get( 'unicode', str )`
I think the intended code was 
`unicode = globals().get( 'unicode', str )`
Although, this doesn't make sense since in Python 2, unicode is a type and not a global variable.  So get() never finds 'unicode' in globals() and always returns str.
I would recommend the following instead
`unicode = type(u'unicode')`

**Comment by enggRosh** [comment]
i did this 'unicode = type(u'unicode')' but it didn't work.

I tried to run the same miniedit.py script in both ubuntu 20 and 22, but none of them work.
