### ISSUE TITLE
KeyError: 'hosts'

### ISSUE THREAD

**Issue by GexLoong** [mininet/mininet#1214]
When I open a .mn file, error
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
>     return self.func(*args)
>   File "miniedit.py", line 1486, in loadTopology
>     hosts = loadedTopology['hosts']
> KeyError: 'hosts'

mininet v 2.3.1  
OS：ubuntu 20.04.5

**Comment by whitefg** [comment]
Please ask me how I solved it in the end.

**Comment by Nelson-iitp** [comment]
remove ```self.convertJsonUnicode``` call in line [1444](https://github.com/mininet/mininet/blob/6eb8973c0bfd13c25c244a3871130c5e36b5fbd7/examples/miniedit.py#L1444) of ```mininet.py```
instead of ```loadedTopology = self.convertJsonUnicode(json.load(f))```
just use ```loadedTopology = json.load(f)```

the ```loadedTopology``` dict keys are loaded as bytes when using ```convertJsonUnicode``` 
which should actually be strings.

**Comment by PumPuiEvo** [comment]
it's work for me thanks!
