### ISSUE TITLE
Issues when exporting 

### ISSUE THREAD

**Issue by Ibets** [mininet/mininet#1225]
### Expected/Desired Behavior:
I expected that when i export into python , it will work , but it wont in my case 

### Actual Behavior:
![VirtualBox_Linux Ubuntu_22_04_2024_11_17_37](https://github.com/mininet/mininet/assets/91409909/d613b177-e8de-4e58-a409-c575c1e714b5)

Like this will be the error , cant concatenate .

### Detailed Steps to Reproduce the Behavior:
I opened miniedit and tried to put topology with 2 host and 2 switches and tried to save it , but when i export it , it just doesnt work

**Comment by Nelson-iitp** [comment]
https://github.com/mininet/mininet/issues/1086#issuecomment-2094575074
