### ISSUE TITLE
Regarding installing mininet in my local ubuntu system!

### ISSUE THREAD

**Issue by Milstein** [mininet/mininet#273]
Hi there,

I got one weird issue 
https://github.com/mininet/mininet/wiki/environment-setup
Tried to install mininet on my local ubuntu  13.10 but when I press enter with :
git clone git://github.com/mininet/mininet

it displays:

Cloning into 'mininet'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out

Why my system is unable to connect github.com?

Milson
http://milson.com.np

**Comment by wuming79** [comment]
Hi, is https://github.com/mininet/mininet.git supposed to take very long to clone? My screen now is stuck at Cloning into 'mininet'... for quite some time. I can't tell if the cloning is still in progress or not without ctrl+z..

**Comment by hwchiu** [comment]
Hi @wuming79 .

It only takes me about 10 seconds to clone whole mininet repository, could you check your networks?
What is the RTT from you host to 'github.com' ?

**Comment by wuming79** [comment]
I got Connection timed out during cloning with message "fatal: unable to access" Failed to connect to github.com port 443:

**Comment by hwchiu** [comment]
I guess there's a network problem between you and 'github.com'.
Could you clone the other repositories well now ?

**Comment by wuming79** [comment]
Tried cloning https://github.com/noxrepo/pox.git and also failed. I suspect something to do with the proxy. I'm doing with via virtualbox too..

**Comment by wuming79** [comment]
I'm back at home. Just tried cloning again. 443 error is no more but now encountering ""fatal: unable to access" Failed to connect to github.com : Could not resolve ost: github"
