### ISSUE TITLE
fatal: unable to connect to openflowswitch.org

### ISSUE THREAD

**Issue by danieledc** [mininet/mininet#277]
Hi everyone, 
since yesterday afternoon I have been trying installing mininet on my new virtual machine but every time I get this error message:

```
Cloning into 'openflow'...
fatal: unable to connect to openflowswitch.org:
openflowswitch.org[0: 171.64.74.58]: errno=Connection timed out
```

I don't understand whether it's my fault or not.

Any suggestions are welcomed.
Thanks in advance,
-Daniele

**Comment by lmaycotte** [comment]
I had the same issue and just updated the install file to clone with https, for ex. 
https://github.com/mininet/openflow.git
Also, some repos may be out of date in the install file, see,
https://mailman.stanford.edu/pipermail/mininet-discuss/2015-May/006124.html
