### ISSUE TITLE
Mininet startup/shutdown can be very slow

### ISSUE THREAD

**Issue by lantz** [mininet/mininet#42]
Particularly on a VM, mininet startup is extremely slow. Adding links and starting switches can be very sluggish.

It seems that Mininet cs244/2.0 might even be slower than 1.0? Or perhaps it just takes up more CPU/memory?

We should add some Mininet startup/shutdown performance benchmarks, and also attempt to identify and fix the cause of the slowdown.

**Comment by cheriimoya** [comment]
`sudo mn --topo torus,10,10 --test build` results in `completed in 25.852 seconds`, was it faster in 1.0? is this still relevant? it seems like startup time on a recent machine is not a problem anymore

**Comment by lantz** [comment]
I declare it good enough for government work.
