### ISSUE TITLE
Running mininet with "--nat" on a remote machine might disconnect you from that machine

### ISSUE THREAD

**Issue by pavlin-r** [mininet/mininet#437]
It seems that running `mn` on a remote machine with `--nat` command-line option might disconnect
you from that machine. E.g.:

```
user@remotemachine[7] sudo mn --controller=remote --mac --nat
*** Creating network
*** Adding controller
Unable to contact the remote controller at 127.0.0.1:6633
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
Write failed: Broken pipe
Exit 255    ### <------ The SSH session disconnects here
user@localmachine[8]
```

Apparently, the `--nat` option automatically adds `10.0.0.0/8` routing entry
(note that the remote machine itself is connected to `10.128.0.0/16` subnet):

```
user@remotemachine[2] netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.128.0.1      0.0.0.0         UG        0 0          0 eth0
10.0.0.0        0.0.0.0         255.0.0.0       U         0 0          0 nat0-eth0
10.128.0.0      0.0.0.0         255.255.0.0     U         0 0          0 eth0
```

In my case, my local machine was coming from `10.1.x.x` address space, and because
of the `10.0.0.0/8` routing entry added by `--nat`, I couldn't connect to the remote machine anymore.
Also, the `mn -h` command-line help didn't tell me about this `--nat` side effect:

```
  --nat                 adds a NAT to the topology that connects Mininet to
                        the physical network
```

Some suggestions how to address the issue:
 a) Add a mandatory argument after `--nat` to specify the NAT-ed IP prefix
 b) Add an optional argument after `--nat` to specify the NAT-ed IP prefix, and in the
     command-line help output the default value (e.g., `10.0.0.0/8`)
In both (a) and (b), the command-line help should also explicitly tell the user about the danger
of the `--nat` side effect.

**Comment by cloudlakecho** [comment]
@pavlin-r Thanks for sharing your error. I am experience similar problem. What Mininet version did you use? 
&emsp; Mine is 2.2.2. 

Also have you tried @lantz  suggestion of `--nat inetIntf=eth0,subnet=10.0/24` in Python code? 
&emsp; If yes, would you share the code line(s)?
