### ISSUE TITLE
Ubuntu Issue: Clean install of Ubuntu 12.04.5 creates unusable apt due to hash mismatch

### ISSUE THREAD

**Issue by lantz** [mininet/mininet#438]
Horrible upstream issue with Ubuntu 12.04.5 - if you install it from the iso, `apt-get update` just doesn't work!! For example:

```
W: Failed to fetch bzip2:/var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_precise_multiverse_binary-i386_Packages  Hash Sum mismatch  
```

This is a very irritating problem and it happens with the canonical (literally) server `us.archive.ubuntu.com`. Clearly it needs to be fixed on their end. A workaround is to boot the VM and run:

```
sudo rm -rf /var/lib/apt/lists/*
sudo apt-get update
sync
sudo shutdown -h now
```

update via @dino74 :
Launchpad bug (and possible diagnosis/fix recommendation) at:
https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1430648

**Comment by dino74** [comment]
Just in case you were wondering what is causing this bug
https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1430648

**Comment by lantz** [comment]
Aha, great! Sounds like they should be able to fix it without too much difficulty. It is amazing that `apt-get` has been broken for so long on 12.04 !!

**Comment by janev94** [comment]
@lantz this works with the latest versions of Ubuntu. Consider closing this.

**Comment by lantz** [comment]
Although personally I'd like Ubuntu 12 to still be usable for reproducing legacy experiments, I agree that current Mininet does not support Ubuntu 12, so we can close this.

**Comment by janev94** [comment]
For reproducibility sake - I have compiled mininet from source whenever the apt manager did not have a compatible copy and that seemed to always work thus far.
