### ISSUE TITLE
Is it possible to run program at host dealing with low layer packet

### ISSUE THREAD

**Issue by goocher** [mininet/mininet#465]
Host in mininet can be considered as a bash which can run any linux program as I know

However what I'm trying to do is implementing some functions at layer 2 such as framing, media access control, or reimplement the TCP/UDP protocol in mininet at host

In current settings. The application I write and run at mininnet host is sitting at application layer and can only use socket interface. The lowest level I can get is just raw socket and no more.

So it's not possible to do that right?
Is mininet core team trying to provide features at this direction in the future?

**Comment by lantz** [comment]
Please don't abuse github issues by submitting random questions. :(
