### ISSUE TITLE
"of && (of.type != 3) && (of.type != 2)" isn't a valid display filter: Neither "of.type" nor "3" are field or protocol names.

### ISSUE THREAD

**Issue by Emil-G** [mininet/mininet#468]
On the latest mininet image (2.2.0) that comes bundled with Wireshark. The command provided to ignore keep alive packets is not working. 

"of && (of.type != 3) && (of.type != 2)" from https://github.com/mininet/openflow-tutorial/wiki/Learn-Development-Tools 

Is resulting in the following error""of && (of.type != 3) && (of.type != 2)" isn't a valid display filter: Neither "of.type" nor "3" are field or protocol names."

**Comment by lantz** [comment]
I've updated it, but remember that since it's a wiki you can fix it yourself!

**Comment by Emil-G** [comment]
Yes, found that out. As it still contained an error. But it should be fixed now.
