### ISSUE TITLE
Possible incompatibility with iperf 3.x (opensuse)

### ISSUE THREAD

**Issue by Hesam-Naderi-Dehkordi** [mininet/mininet#471]
I 've installed mininet and all dependecies in opensuse manually by following the install script. After running mininet with no arguments and options, I had tested ping and connectivity  and h1 can ping h2 and vise versa, but when trying to test the performance , "iperf h1 h2" and got this response repeatedly : "Waiting for iperf to start up..." and nothing happens until pressing CNTR+C.
I have used diffrent switches like ovsk,ivs,ovs and no diffrence.
I have tested iperf manualy by opening xterm of two hosts and checking iperf by using one in server mode and another in client mode and it works like a charm!

Does anybody know what's wrong and why iperf doesn't work in Mininet shell ?

**Comment by lantz** [comment]
So, this is going a bit outside the average use case since you're using it on a platform that isn't Ubuntu or Fedora, but here are some questions for you to see if you can debug it a bit:

1. Are you sure that you've installed `telnet` as well as `iperf`, as is done in the install script?

2. Since you're using OpenSuse, do `telnet` and `iperf` produce the same output that they do on Ubuntu?

3. When you run Mininet with `mn -v debug`, what are the results you are seeing?

**Comment by lantz** [comment]
Incidentally, you are welcome to make a pull request to add OpenSuse support to `install.sh`.

**Comment by Hesam-Naderi-Dehkordi** [comment]
Telnet and iperf are installed before and worked correctly independently. Both of the outputs are similar to each other.
Here is output of mn -v debug :
*** Setting resource limits
*** Creating network
*** Adding controller
*** c0 : ('stty -echo',)
mnexec -p stty -echo
*** c0 : ('set +m',)
*** c0 : ('echo A | telnet -e A 127.0.0.1 6633',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts:
*** h1 : ('stty -echo',)
mnexec -p stty -echo
*** h1 : ('set +m',)
h1 *** h2 : ('stty -echo',)
mnexec -p stty -echo
*** h2 : ('set +m',)
h2 
*** Adding switches:
*** s1 : ('stty -echo',)
stty -echo
*** s1 : ('set +m',)

added intf lo (0) to node s1
*** s1 : ('ifconfig', 'lo', 'up')
s1 
*** Adding links:

added intf h1-eth0 (0) to node h1
moving h1-eth0 into namespace for h1 
*** h1 : ('ifconfig', 'h1-eth0', 'up')

added intf s1-eth1 (1) to node s1
*** s1 : ('ifconfig', 's1-eth1', 'up')
(h1, s1) 
added intf h2-eth0 (0) to node h2
moving h2-eth0 into namespace for h2 
*** h2 : ('ifconfig', 'h2-eth0', 'up')

added intf s1-eth2 (2) to node s1
*** s1 : ('ifconfig', 's1-eth2', 'up')
(h2, s1) 
*** Configuring hosts
h1 *** h1 : ('ifconfig', 'h1-eth0', '10.0.0.1/8', 'up')
*** h1 : ('ifconfig lo up',)
h2 *** h2 : ('ifconfig', 'h2-eth0', '10.0.0.2/8', 'up')
*** h2 : ('ifconfig lo up',)

*** Starting controller
c0 *** c0 : ('controller -v ptcp:6633 1>/tmp/c0.log 2>/tmp/c0.log &',)
[1] 2726

*** Starting 1 switches
s1 *** s1 : ('ovs-vsctl del-br', <OVSSwitch s1: lo:127.0.0.1,s1-eth1:None,s1-eth2:None pid=2616> )
ovs-vsctl: no bridge named s1
*** s1 : ('ovs-vsctl -- get Bridge', <OVSSwitch s1: lo:127.0.0.1,s1-eth1:None,s1-eth2:None pid=2616> , 'Controller')
ovs-vsctl: no row "s1" in table Bridge
*** s1 : ('ovs-vsctl add-br s1 -- set Bridge s1 other_config:datapath-id=0000000000000001 -- set-fail-mode s1 secure -- add-port s1 s1-eth1 -- set Interface s1-eth1 ofport_request=1  -- add-port s1 s1-eth2 -- set Interface s1-eth2 ofport_request=2 -- set-controller s1 tcp:127.0.0.1:6633 ptcp:6634 -- set bridge s1 other-config:disable-in-band=true ',)


----------------------------------------------------------------------------------
Opensuse :*** Setting resource limits
*** Creating network
*** Adding controller
*** c0 : ('stty -echo',)
mnexec -p stty -echo
*** c0 : ('set +m',)
*** c0 : ('echo A | telnet -e A 127.0.0.1 6633',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
*** Adding hosts:
*** h1 : ('stty -echo',)
mnexec -p stty -echo
*** h1 : ('set +m',)
h1 *** h2 : ('stty -echo',)
mnexec -p stty -echo
*** h2 : ('set +m',)
h2 
*** Adding switches:
*** s1 : ('stty -echo',)
stty -echo
*** s1 : ('set +m',)

added intf lo (0) to node s1
*** s1 : ('ifconfig', 'lo', 'up')
s1 
*** Adding links:
*** h1 : ('ip link add name h1-eth0 address d2:14:7c:ff:f9:f8 type veth peer name s1-eth1 address 96:62:a8:a1:19:9d netns 6814',)

added intf h1-eth0 (0) to node h1
moving h1-eth0 into namespace for h1 
*** h1 : ('ifconfig', 'h1-eth0', 'up')

added intf s1-eth1 (1) to node s1
*** s1 : ('ifconfig', 's1-eth1', 'up')
(h1, s1) *** h2 : ('ip link add name h2-eth0 address da:f8:80:1b:90:aa type veth peer name s1-eth2 address 82:33:90:b6:a9:af netns 6814',)

added intf h2-eth0 (0) to node h2
moving h2-eth0 into namespace for h2 
*** h2 : ('ifconfig', 'h2-eth0', 'up')

added intf s1-eth2 (2) to node s1
*** s1 : ('ifconfig', 's1-eth2', 'up')
(h2, s1) 
*** Configuring hosts
h1 *** h1 : ('ifconfig', 'h1-eth0', '10.0.0.1/8', 'up')
*** h1 : ('ifconfig lo up',)
h2 *** h2 : ('ifconfig', 'h2-eth0', '10.0.0.2/8', 'up')
*** h2 : ('ifconfig lo up',)

*** Starting controller
c0 *** c0 : ('controller -v ptcp:6633 1>/tmp/c0.log 2>/tmp/c0.log &',)

*** Starting 1 switches
s1 *** s1 : ('ovs-vsctl --if-exists del-br s1 -- add-br s1 -- set Bridge s1 other_config:datapath-id=0000000000000001 -- set-fail-mode s1 secure -- add-port s1 s1-eth1 -- set Interface s1-eth1 ofport_request=1  -- add-port s1 s1-eth2 -- set Interface s1-eth2 ofport_request=2 -- set-controller s1 tcp:127.0.0.1:6633 ptcp:6634 -- set bridge s1 other-config:disable-in-band=true ',)
*** s1 : ('ovs-vsctl -- get Bridge', <OVSSwitch s1: lo:127.0.0.1,s1-eth1:None,s1-eth2:None pid=6814> , 'Controller')
[20ba4b80-4f50-411d-be11-8ea3077b0d6f, 5d6dfed8-fd7c-43a0-9ece-e2e0932b12c8]
*** s1 : ('ovs-vsctl', '-- set Controller 20ba4b80-4f50-411d-be11-8ea3077b0d6f max_backoff=1000', '-- set Controller 5d6dfed8-fd7c-43a0-9ece-e2e0932b12c8 max_backoff=1000')

**Comment by Hesam-Naderi-Dehkordi** [comment]
I found the problem. It's because of iperf version.
in opensuse it's 3.0.10 after installing version 2.0.5 it works again in mininet shell.

I had installed V3. it makes iperf3 executable but after I had linked an iperf link with iperf3 it didn't worked yet.
any solution or workaround for version 3?

**Comment by lantz** [comment]
I don't have a solution offhand - if you come up with one, feel free to submit a pull request.

Also your output doesn't include the results from running iperf, e.g. `sudo mn -v debug --test iperf`

**Comment by Hesam-Naderi-Dehkordi** [comment]
I found that there are some differences with iperf2 and iperf3.
The first is in the listening port for server. Iperf2 use port 5001 and iperf3 use port 5201.
The second is the output difference to parse. Iperf2 calculate the bandwidth only once without any argument, but iperf3 calculate it about ten times, print them and in the end it outputs the average.
In the "net.py" file port is mentioned statically in iperf function : 'sh -c "echo A | telnet -e A %s 5001"'. I don't think it's necessary and it is the cause of problem. I 'm not a master in python and could not manipulate "net.py" so well to handle iperf3 and iperf2 outputs for printing them in mininet shell.

And dear lantz, about your pull request for opensuse , it was somehow difficult, because of some outdated dependencies that are bind to old libraries that are not present anymore in newest opensuse repositories (opensuse 13.1 , 13.2,...) like old swig and bison (swig 1.3 ,bison 2.5) or some errors for compilations of old codes so need to add some flags in compilations, or do adding some "include...." in the codes and so on.
It took me about 7-8 hours to installing mininet and all dependecies but then it worked like a charm , without any problem, with the newest libraries and builds.
I can interpret the install script so well but don't have a good skill in writing scripts to do all that do manually to make the script compatible with opensuse .
But I can present you my virtual machine or anybody who wants mininet in opensuse. (It's about 3.6 GB, a bit large, because of desktop managers like KDE and GNOME).

**Comment by lantz** [comment]
Hmm.... well if you want to tackle updating for an OpenSuse install, that would be helpful.

Otherwise, maybe someone else will be able to figure it out.

I have slightly modified `iperf()` in b2fe0778dc21ccc772292e5337f388446c4ce8f4 to explicitly supply a port argument. However, if the output format is different for `iperf` 3, then additional modifications may be required.
