### ISSUE TITLE
Meter Tables

### ISSUE THREAD

**Issue by imehrdad2012** [mininet/mininet#476]
Hello,

I am trying to use meters (rate-limiters) by adding them to flow entries. I am using 
the latest RYU and Mininet. However, it seems when the flow mods are installed into
the tables, I get some errors similar to the following. Thus my question is if this is OVS
limitation or this is specific to Mininet implementation?

OFPErrorMsg(code=10,data='\x04\x1d\x00 \xf7\xcd@\x0e\x00\x00\x00\x01\x00\x00\x00\x02\x00\x01\x00\x10\x00\x00\x01\xf4\x00\x00\x00\x05\x00\x00\x00\x00',type=12) type 0xc code 0xa 0x4 0x1d 0x0 0x20 0xf7 0xcd 0x40 0xe 0x0 0x0 0x0 0x1 0x0 0x0 0x0 0x2 0x0 0x1 0x0 0x10 0x0 0x0 0x1 0xf4 0x0 0x0 0x0 0x5 0x0 0x0 0x0 0

**Comment by lantz** [comment]
I think you may be misunderstanding something - Mininet is an orchestration system that uses a variety of software switches. It doesn't dictate the functionality of the switches themselves.

Can you

1. Confirm that you have installed and are running the latest version of Open vSwitch (2.3.1)?

2. Confirm that OVS does in fact support the operations you are using?

3. Decode the error message and confirm (absolutely) that you haven't made any mistakes yourself and hat OVS is exhibiting erroneous behavior?

4. Confirm that the problem either does or does not occur with the CpqD OpenFlow switch?

Thanks.

**Comment by imehrdad2012** [comment]
Thanks Bob!
Given I have used your installations scripts, I thought you might use a
specific or customized OVS software switch.

1- I can confirm that I am using the latest OVS
2- Unfortunately, I just figured out OVS does not implement the meter
tables.
3- The decoded message says there is not any OF meters in OVS
4- I learnt this CpqD switch supports the meters. However, I am not sure
how to conveniently use it in my Mininnet scripts. Could you please point
where to start for using CpqD switches? Can I just pass the switch type to
Mininet if it already encapsulate such a switch?

Best Regards,
---Mehrdad






On Thu, Feb 19, 2015 at 2:52 PM, lantz <notifications@github.com> wrote:

> I think you may be misunderstanding something - Mininet is an
> orchestration system that uses a variety of software switches. It doesn't
> dictate the functionality of the switches themselves.
>
> Can you
>
>    1.
>
>    Confirm that you have installed and are running the latest version of
>    Open vSwitch (2.3.1)?
>    2.
>
>    Confirm that OVS does in fact support the operations you are using?
>    3.
>
>    Decode the error message and confirm (absolutely) that you haven't
>    made any mistakes yourself and hat OVS is exhibiting erroneous behavior?
>    4.
>
>    Confirm that the problem either does or does not occur with the CpqD
>    OpenFlow switch?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mininet/mininet/issues/476#issuecomment-75123307>.
>



-- 
-----
Mehrdad Moradi
‌Research Assistant
University of Michigan- Ann Arbor

**Comment by lantz** [comment]
If you install the CpqD switch and it's in your path, it replaces `--switch user`.
