### ISSUE TITLE
Unable to deploy mininet ovf on ESXi 5.0 and ESXi5.5

### ISSUE THREAD

**Issue by abhsob** [mininet/mininet#483]
Get an error: 
Not a supported disk format (sparse VMDK version too old)

**Comment by lantz** [comment]
Can you confirm that you were unable to convert the VMDK using VMware's utilities?

**Comment by abhsob** [comment]
I was able to load the VMDK on ESXi 5.5 server without needing any conversion. Thanks for the followup on this issue.

**Comment by wanglf** [comment]
I encountered same problem both in Vmware ESXI 4.1.0 and ESXi 5.5.0. Finally, I use Vmware ovftool to convert the ovf file, problem solves.

**Comment by hellt** [comment]
@wanglf what command did you use to convert ovf template?
