### ISSUE TITLE
not able to install mininet in VirtualBox

### ISSUE THREAD

**Issue by karthikhmk** [mininet/mininet#486]
when i am trying to install mininet on VirtualBox. i am getting error when i run it. please find attached screen shot of the error.

![image](https://cloud.githubusercontent.com/assets/11422090/6594266/8bc0af4e-c7ad-11e4-9e98-803858f3d664.png)
![image](https://cloud.githubusercontent.com/assets/11422090/6594280/be710fce-c7ad-11e4-9578-f48231e60e2b.png)

**Comment by lantz** [comment]
This appears to be a problem with VirtualBox.

Can you please confirm that you can start up other Ubuntu VMs in VirtualBox?

**Comment by lantz** [comment]
Closing because of no reply.
