### ISSUE TITLE
Is Cbench topology aware ?

### ISSUE THREAD

**Issue by milangroshev** [mininet/mininet#500]
Hi to all... 

I have a question regarding Cbench... as i read in some papers  Cbench is a benchmark tool developed to evaluate the performance of OpenFlow controllers. By taking advantage of the Cbench, it is possible to identify performance improvements for OpenFlow controllers based on different environment and system configurations, such as the number of forwarding devices, network topology, overall network workload, type of equipments, forwarding complexity, and overhead of the applications being executed on top of controllers

Is it true that Cbench is topology aware? and how can that be done? All i can see Cbench just generates big amount of packet_in messages with different MAC address and do some computations on the packet_out... he is not topology aware and you can not choose the topology 

If somebody has answer to this please write to me :D

**Comment by lantz** [comment]
Please only use github issues for Mininet bugs and feature requests, thanks!

Comments and questions on `cbench` should probably go do `openflow-discuss`.
