### ISSUE TITLE
Bug in getNodeByName()/get() in net.py

### ISSUE THREAD

**Issue by 5hizzle** [mininet/mininet#503]
Hi
I have been getting KeyErrors when retrieving Node objects from my Mininet instance 'net'.
Here is the code passage of interest

    def _makeRouter(self):
        info('*** Adding Router\n')
        router = self.net.addSwitch('s%d' % self.sitePrefix, cls=OVSSwitch, protocols='OpenFlow13')
        print self.net.nameToNode
        print router
        print 's1'
        print self.net.nameToNode['s1'].IP()
        print self.net.nameToNode[router].IP()

and here is the console output for these lines

*** Adding Router
{'e99': &#60;OVSSwitch e99: lo:127.0.0.1 pid=11133&#62; , 'h11': &#60;Host h11:  pid=11138&#62; , 's1': &#60;OVSSwitch s1: lo:127.0.0.1 pid=11141&#62; , 'floodlight_controller': &#60;RemoteController floodlight_controller: 192.168.56.1:6653 pid=11125&#62; }
s1
s1
127.0.0.1
Traceback (most recent call last):
...
  File "./autonaas_topo.py", line 72, in _makeRouter
    print self.net.nameToNode[router].IP()
KeyError: &#60;OVSSwitch s1: lo:127.0.0.1 pid=11141&#62; 

Apparently I can only use self.net.nameToNode['s1'] to retrieve Switch s1 while the methods in the title are failing...

Can this be fixed?

Best,
Damo

**Comment by lantz** [comment]
The error is correct and your code is not.

Could you please close this? Thanks.

**Comment by lantz** [comment]
p.s. Recall that `print x` is the same as `print str(x)` if `x` is an object.

**Comment by 5hizzle** [comment]
Yes, you are right, getting the same for print 's1' and router as well as getting the object i was looking for in the KeyError has lead to quite a bit of confusion... Thank you!
