### ISSUE TITLE
Mininet constructor: intf option is not effective

### ISSUE THREAD

**Issue by yoursunny** [mininet/mininet#515]
Mininet constructor accepts 'intf' option, described as:

> intf: default Intf class/constructor

but this option is not effective.
Constructed interface is always `mininet.link.Intf` type, unless 'link' option is overridden with a subclass.

Snippet to reproduce:

```
from mininet.topo import MinimalTopo
from mininet.net import Mininet
from mininet.node import Intf

class MyIntf(Intf):
    def __init__(self, *opts, **params):
        Intf.__init__(self, opts, params)

topo = MinimalTopo()
net = Mininet(topo, intf=MyIntf)
net.start()
print type(net.hosts[0].intf())
net.stop()
```

Expected: `<class 'MyIntf'>`  
Actual: `<class 'mininet.link.Intf'>`

**Comment by lantz** [comment]
```#!/usr/bin/python

from mininet.topo import MinimalTopo
from mininet.net import Mininet
from mininet.link import TCIntf

topo = MinimalTopo()
net = Mininet(topo, intf=TCIntf)
net.start()
print type(net.hosts[0].intf())
net.stop()
openflow@ubuntu13:~$ sudo python intftest.py
<class 'mininet.link.TCIntf'>```

**Comment by yoursunny** [comment]
Yes this issue was indeed discovered when I attempted to use `TCIntf`. I found `TCLink` afterwards, but believed there would be legit cases when `intf=` would be useful.
Thanks for quick response!
