### ISSUE TITLE
git links in install.sh not working - unable to install

### ISSUE THREAD

**Issue by loffler** [mininet/mininet#517]
I tried to install mininet from source (./install.sh), but an error occured:
```
Cloning into 'openflow'...
fatal: read error: Connection reset by peer
(the install script is attempting to clone from git://openflowswitch.org/openflow.git)
```
according to infomation on top of the page on  http://archive.openflow.org/ (where I am being redirected when trying to visit openflowswitch.org), this site is no longer maintained.
I think we should change the dead links in install.sh to working ones. I would do it, but as I am new to mininet and openflow,  I don't know what are the proper locations.

the line which is causing the problem:
```
https://github.com/mininet/mininet/blob/master/util/install.sh#L164
```
(there was similar issue some time ago: https://github.com/mininet/mininet/issues/277 , but it seemed to be a temporal problem only)

**Comment by hu6360567** [comment]
remove the 651 line in install.sh should work

**Comment by lantz** [comment]
This isn't really a bug - rather, the server is simply offline.

If you don't need the reference switch and controller, you can simply use

    install.sh -nv

**Comment by basavesh** [comment]
Hi,
Even I had faced these issues. As a workaround I edited the script to clone a forked repo.
Workaround: replace that line with "git clone https://github.com/noxrepo/openflow.git"

Suggestion: It might be good to have a fork of that repo in mininet github itself, as original thing is archived.

**Comment by lantz** [comment]
Technically not - the git repo at Stanford is still operational, but I kind of agree that development has largely stopped so we can use our fork.

**Comment by lmaycotte** [comment]
I had to update the install file to clone with https, for ex. 
https://github.com/mininet/openflow.git
Also, some repos may be out of date in the install file that may need to be updated, see,
https://mailman.stanford.edu/pipermail/mininet-discuss/2015-May/006124.html

**Comment by lantz** [comment]
Using https shouldn't be necessary unless your network blocks git - in which case you should really use another network.

**Comment by sinhayash** [comment]
See my comment in #573

**Comment by sahilshekhawat** [comment]
cloning https://github.com/mininet/openflow.git instead of the default do fixes this and this is still not fixed in master.

**Comment by sahilshekhawat** [comment]
And this error comes with "oflops" too. I think that we can replace links with mirrors on github that we have.

**Comment by point-h2020** [comment]
there is a github mirror for oflops as well on: https://github.com/mininet/oflops
replace the oflop clone repo (line 556 in install.sh) with the mirror and should work.

**Comment by sahilshekhawat** [comment]
That's exactly what I did but shouldnt we be fixing the install.sh itself?

**Comment by sinhayash** [comment]
Pull request pending already

**Comment by mfhaln** [comment]
absolutely agree, the clone links should be changed to github mirrors rather than manual editing of links everytime one tries to install.

**Comment by lantz** [comment]
This was done in 312ed1a4a53135eaf3b446bd94e80ebeefa20b8c
