### ISSUE TITLE
Multiple Controller Support

### ISSUE THREAD

**Issue by sgmace** [mininet/mininet#518]
Mininet CLI currently do not support multiple controllers. Also there are no commands to check the roles pushed by controller.

**Comment by lantz** [comment]
These statements are inaccurate, because:

1. `mn` accepts multiple `--controller` arguments
2. `ovs-vsctl` can be used to check the controller role

**Comment by sgmace** [comment]
Oh I did not know about statement 1.
I have developed a CLI to check the role. Thinking of submitting to
community.

**Comment by lantz** [comment]
OK, if you have a pull request, feel free to submit it. Closing for now.
