### ISSUE TITLE
Mininet high-level CLI performance issue

### ISSUE THREAD

**Issue by Emil-G** [mininet/mininet#519]
Hi

Using the latest release of *Mininet 2.2.1* I have encountered a strange performance bug/limitation that I can't figure out. I am doing performance tests of different load balancing algorithms and have for that case create a High-level python script to boot the network. 

In the script staring a server is done like so: **h3.cmd('http-server -p 80 &').**

Running a httperf test gives this result, where as a lot of requests times out and gives error:

[Automatic started]
*Total: connections 2520 requests 830 replies 555 test-duration 133.878s
Request rate: 6.2 req/s (161.3 ms/req)
Errors: total 1965 lient-timo 1965 socket-timo 0 connrefused 0 connreset 0*
[end]

But if I start a xterm for h3: "xterm h3" and then type in **"http-server -p 80"** this is the result for the same httperf test:

[Manually started]
*Total: connections 2520 requests 2520 replies 2520 test-duration 126.051s
Request rate: 20.0 req/s (50.0 ms/req)
Errors: total 0 client-timo 0 socket-timo 0 connrefused 0 connreset 0*
[end]

I don't really get why the performance should differ, it is as there is some sort of limit on background process initiated this way. I have tested multiple terminal web-servers and they all act in the same way. 

Any ideas to why this is happening?

**Comment by lantz** [comment]
Can you confirm that `http-server` generates no output?

If it generates output, then you should not run it using `h3.cmd('http-server -p 80 &')` or it will eventually block until you read the output.

**Comment by Emil-G** [comment]
It generates output... is there in that case any way of disabling that it blocks?

**Comment by lantz** [comment]
Potentially by modifying your server to not write anything if it would block. Usually, you have to either read or redirect the output. This is a really feature of the way Unix pipe I/O works, and it should not be surprising.

**Comment by lantz** [comment]
For this reason, it's really not a sensible idea to use `cmd` to run something in the background that generates output, unless you redirect the output somewhere.
