### ISSUE TITLE
String Argument Error Breaks Mininet

### ISSUE THREAD

**Issue by gmiotto** [mininet/mininet#520]
The last IF in the function below, on file `node.py` at line 1146, an argument is passed to the string
    `opts += ' stp_enable=true' % self`
but the string does not have any arguments.
    
    def bridgeOpts( self ):
        "Return OVS bridge options"
        opts = ( ' other_config:datapath-id=%s' % self.dpid +
                 ' fail_mode=%s' % self.failMode )
        if not self.inband:
            opts += ' other-config:disable-in-band=true'
        if self.datapath == 'user':
            opts += ' datapath_type=netdev'
        if self.protocols and not self.isOldOVS():
            opts += ' protocols=%s' % self.protocols
        if self.stp and self.failMode == 'standalone':
            opts += ' stp_enable=true' % self 
        return opts

Simply removing the argument fixes this bug and the error stops.

**Comment by lantz** [comment]
1. Hmm, this does appear to be a regression.
2. Why is this an issue and not a pull request? ;-)
