### ISSUE TITLE
Problem in running Mininet in docker

### ISSUE THREAD

**Issue by imehrdad2012** [mininet/mininet#529]
Hello,

I am trying to run the mininet within an ubuntu container using docker. However, I cannot run any of the examples successfully. These are the commands I have used:
1) sudo docker run -it --name="ubuntu_ovs" ubuntu:latest /bin/bash
2) root@66167533a128:/# sudo apt-get update
3) root@66167533a128:/# sudo apt-get install mininet
4) root@66167533a128:/# sudo apt-get install git
5) root@66167533a128:/# git clone git://github.com/mininet/mininet.git
6) root@66167533a128:/# cd mininet/examples
7) root@66167533a128:/mininet/examples# sudo python nat.py

I get the following errors for all examples in the folder. Do you have any idea what the problem is?

*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 h3 h4
*** Adding switches:
s1
*** Adding links:
Traceback (most recent call last):
  File "nat.py", line 104, in <module>
    net = TreeNet( depth=1, fanout=4 )
  File "/usr/lib/python2.7/dist-packages/mininet/topolib.py", line 36, in TreeNet
    return Mininet( topo, **kwargs )
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 164, in __init__
    self.build()
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 357, in build
    self.buildFromTopo( self.topo )
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 344, in buildFromTopo
    self.addLink( src, dst, srcPort, dstPort, **params )
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 287, in addLink
    return cls( node1, node2, **defaults )
  File "/usr/lib/python2.7/dist-packages/mininet/link.py", line 362, in __init__
    link=self, **params1  )
  File "/usr/lib/python2.7/dist-packages/mininet/link.py", line 45, in __init__
    node.addIntf( self, port=port )
  File "/usr/lib/python2.7/dist-packages/mininet/node.py", line 355, in addIntf
    moveIntf( intf.name, self )
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 202, in moveIntf
    srcNode=srcNode, printError=printError )
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 167, in retry
    while not fn( *args, **keywords ) and tries < retries:
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 186, in moveIntfNoRetry
    links = dstNode.cmd( 'ip link show' )
  File "/usr/lib/python2.7/dist-packages/mininet/node.py", line 283, in cmd
    self.sendCmd( *args, **kwargs )
  File "/usr/lib/python2.7/dist-packages/mininet/node.py", line 229, in sendCmd
    self.write( cmd + '\n' )
  File "/usr/lib/python2.7/dist-packages/mininet/node.py", line 182, in write
    os.write( self.stdin.fileno(), data )
OSError: [Errno 32] Broken pipe

These are also the outputs after running ovs service start and restart. I can manually add ovs instances without any problem.
root@66167533a128:/mininet/examples# sudo service openvswitch-switch restart
 * Killing ovs-vswitchd (788)
 * Killing ovsdb-server (778)
nice: cannot set niceness: Permission denied
 * Starting ovsdb-server
 * Configuring Open vSwitch system IDs
nice: cannot set niceness: Permission denied
 * Starting ovs-vswitchd
 * Enabling remote OVSDB managers

**Comment by lantz** [comment]
It's likely there is something deficient in your container environment.

1. It works fine for me in a container.
2. The nat.py example is a bit obsolete - please try
    sudo mn --nat
3. To debug the problem, please try
    sudo mn --nat -v debug
4. Please confirm that the following works correctly
    sudo mn --test pingall
    sudo mn --nat -v debug

Thank you.

**Comment by imehrdad2012** [comment]
Thanks Bob.

I have tried this on other machines and were able to reproduce the same problem. I installed a fresh docker and ran the latest official container from DockerHub.  Given the sudo mn --nat was not available in the Mininet 2.1. I got a new container and compiled Mininet by  mininet/util/install.sh -fnv.  

Now the output of sudo mn --nat -v debug is: 

root@d3d74b08aebb:/# sudo mn -v debug
  0*** Setting resource limits
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0*** c0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** errRun: ['which', 'telnet']
/usr/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6633',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts:
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0

**Comment by lantz** [comment]
1. Why are you not using the latest Mininet?
2. That isn't the complete output from `mn --nat -v debug`
3. You should try `mn --nat -v debug --test pingpair` or something

**Comment by imehrdad2012** [comment]
1. I am using the latest Mininet and compiled it successfully based on INSTAL file. I can also confirm OVS works perfectly without any problem.
root@a3c769c17cbd:/# mn --version ---->2.2.1

2. The following is the complete output of "mn --nat v debug". The output freezes at the last line and never goes forward and I have to stop the code with "Ctrl+C".

root@a3c769c17cbd:/# mn --nat -v debug
*** errRun: ['which', 'controller']
/usr/local/bin/controller
  0*** errRun: ['grep', '-c', 'processor', '/proc/cpuinfo']
32
  0*** Setting resource limits
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0*** c0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** errRun: ['which', 'telnet']
/usr/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6633',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts:
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0

3. The complete output for mn --nat -v debug --test pingpair is similar to the above output:

root@a3c769c17cbd:/# mn --nat -v debug --test pingpair
*** errRun: ['which', 'controller']
/usr/local/bin/controller
  0*** errRun: ['grep', '-c', 'processor', '/proc/cpuinfo']
32
  0*** Setting resource limits
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0*** c0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** errRun: ['which', 'telnet']
/usr/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6633',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts:
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0
4. I meant I am using the latest official ubuntu container from dockerhub not Mininet. 

Thanks.

**Comment by lantz** [comment]
That doesn't look like the complete output. Are you saying it's hanging at ifconfig?

**Comment by imehrdad2012** [comment]
Thanks Bob for your help. I really appreciate it. Unfortunately, the code hangs at ifconfig. If I do hit Control+C, it stays there forever. 

1- After I hit Control-C, I get the following output:
root@a3c769c17cbd:/# mn --test pingall -v debug
*** errRun: ['which', 'controller']
/usr/local/bin/controller
  0*** errRun: ['grep', '-c', 'processor', '/proc/cpuinfo']
32
  0*** Setting resource limits
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0*** c0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** errRun: ['which', 'telnet']
/usr/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6633',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts:
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0^C

Keyboard Interrupt. Shutting down and cleaning up...

*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller udpbwtest mnexec ivs 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller udpbwtest mnexec ivs 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** errRun: ['pkill', '-9', '-f', 'mnexec.*socat']
  1*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.

2- Similarly this command (mn --test pingall -v debug) also does not run properly. It seems Mininet cannot completely create the topology to perform the ping operation (take a look at the above output).

3- These are my kernel information: Linux a3c769c17cbd 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux / Distributor ID:Ubuntu Description:	Ubuntu 14.04.2 LTS Release:	14.04 Codename:	trusty.

4-  It seems the output of the command is not what we expect (see below). Do you have any pointer why this happens?

root@a3c769c17cbd:/# sudo mnexec -n ip link show
unshare: Operation not permitted

Thanks a lot!

**Comment by imehrdad2012** [comment]
Thanks Bob. I was able to address the above problem.  I have uploaded my mininet container in dockerhub:
sudo docker pull imehrdad2012/mininet
sudo docker run –privileged=true -it imehrdad2012/mininet

**Comment by lantz** [comment]
That's your problem. Please use a different kernel that has CONFIG_NET_NS enabled.

```
$ uname -r
3.16.0-26-generic
$ grep CONFIG_NET_NS  /boot/config-`uname -r`
CONFIG_NET_NS=y
```

**Comment by Rambou** [comment]
@imehrdad2012 I see that you deleted your minnet container from docker hub? Why? And also i would like to know if its a sensible idea to run mininet on docker at this time, ora completely waste of time?

**Comment by Jan-07** [comment]
@imehrdad2012 What was the solution for this behavior? I'd like to reproduce this test environment and keep getting the same error...

**Comment by MonsieurWave** [comment]
Similar problem experienced here. 
Solution for connecting mininet to internet in docker would be much appreciated.

**Comment by soreana** [comment]
This problem caused when mininet can't set below kernels parameters in docker container.

```
#Increase arp cache size
sysctlTestAndSet( 'net.ipv4.neigh.default.gc_thresh1', 4096 )
sysctlTestAndSet( 'net.ipv4.neigh.default.gc_thresh2', 8192 )
sysctlTestAndSet( 'net.ipv4.neigh.default.gc_thresh3', 16384 )
```

You can fix this problem by sharing host kernel parameters with docker container.
Dockerfile and docker-compose file provided [here](https://github.com/soreana/docker-mininet)

**Comment by JaspreetToro** [comment]
I am also getting the same error in the ubuntu terminal in Windows machine: 

Please fine below the logs: 
sudo mn --version
2.3.0d6
uname -r
4.4.0-17134-Microsoft

sudo mn --nat -v debug

*** errRun: ['which', 'controller']
/usr/local/bin/controller
  0*** errRun: ['grep', '-c', 'processor', '/proc/cpuinfo']
8
  0*** Setting resource limits
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0_popen ['mnexec', '-cd', 'env', 'PS1=\x7f', 'bash', '--norc', '--noediting', '-is', 'mininet:c0'] 540*** c0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** errRun: ['which', 'telnet']
/usr/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6653',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts:
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0_popen ['mnexec', '-cdn', 'env', 'PS1=\x7f', 'bash', '--norc', '--noediting', '-is', 'mininet:h1'] 547


sudo mn --test pingall -v debug


*** errRun: ['which', 'controller']
/usr/local/bin/controller
  0*** errRun: ['grep', '-c', 'processor', '/proc/cpuinfo']
8
  0*** Setting resource limits
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0_popen ['mnexec', '-cd', 'env', 'PS1=\x7f', 'bash', '--norc', '--noediting', '-is', 'mininet:c0'] 587*** c0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** errRun: ['which', 'telnet']
/usr/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6653',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts:
*** errRun: ['which', 'mnexec']
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig']
/sbin/ifconfig
  0_popen ['mnexec', '-cdn', 'env', 'PS1=\x7f', 'bash', '--norc', '--noediting', '-is', 'mininet:h1'] 594

![Error_Mininet](https://user-images.githubusercontent.com/43653684/64914687-13e68f80-d70b-11e9-96c5-a77d73507d71.JPG)

**Comment by JaspreetToro** [comment]
Please suggest the solution for the above issue.

**Comment by lantz** [comment]
This issue has been closed; if you think there is a bug, please open a bug report issue. However, the behavior you are showing doesn't appear to be a bug.

**Comment by alkaneseries** [comment]
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2
*** Adding switches:
s1
*** Adding links:
(h1, s1) (h2, s1)
*** Configuring hosts
h1 h2
*** Starting controller
c0
*** Starting 1 switches


I got the above error after setting up my mininet on Ubuntu 18.04. I am working on a remote server and I have been stuck on this for 3 days, please help me. How may I solve this?

**Comment by soreana** [comment]
@alkaneseries did you checked the following repository? What is your docker file? How do you run it?
https://github.com/iwaseyusuke/docker-mininet

**Comment by alkaneseries** [comment]
I tried everything, still did not work

**Comment by allewwaly** [comment]
I've met the similar problem running mininet with `nat` options in docker, it counters `IOError: [Errno 2] No such file or directory: '/etc/network/interfaces'`, the detail error message is [here](https://github.com/iwaseyusuke/docker-mininet/issues/7). Anybody met the same problem?
