### ISSUE TITLE
Mininet Installation

### ISSUE THREAD

**Issue by NiravToliya** [mininet/mininet#534]
I am new to Mininet and Openflow. I am trying to install mininet in Ubuntu 14.04LTS. 
I typed this command : mininet/util/install.sh -fw 
got error like fatal: repository 'https://openflowswitch.org/openflow.git/' not found when its trying to clone openflow.
what is the solution of this problem...?

**Comment by rnilekani** [comment]
@NiravToliya, How are you installing mininet on your machine? What approach are you using?

http://mininet.org/download/

**Comment by sinhayash** [comment]
See my comment in #573

**Comment by lantz** [comment]
The cause is that yuba is occasionally down.

Using github mirror as of 312ed1a4a53135eaf3b446bd94e80ebeefa20b8c
