### ISSUE TITLE
BGP Path Hijacking lab replication

### ISSUE THREAD

**Issue by rnilekani** [mininet/mininet#535]
I am trying to replicate the lab performed here.
https://github.com/mininet/mininet/wiki/BGP-Path-Hijacking-Attack-Demo

I am getting stuck at step 2:

Step 1: works

mininet@mininet-vm:~/bgp$ sudo python bgp.py 
*** Creating network
*** Adding controller
*** Adding hosts:
h1-1 h1-2 h1-3 h2-1 h2-2 h2-3 h3-1 h3-2 h3-3 h4-1 h4-2 h4-3 
*** Adding switches:
R1 R2 R3 R4 
*** Adding links:
(R1, R2) (R1, R4) (R1, h1-1) (R1, h1-2) (R1, h1-3) (R2, R3) (R2, h2-1) (R2, h2-2) (R2, h2-3) (R3, h3-1) (R3, h3-2) (R3, h3-3) (R4, h4-1) (R4, h4-2) (R4, h4-3) 
*** Configuring hosts
h1-1 h1-2 h1-3 h2-1 h2-2 h2-3 h3-1 h3-2 h3-3 h4-1 h4-2 h4-3 
*** Starting controller
*** Starting 4 switches
R1 R2 R3 R4 
Waiting 3 seconds for sysctl changes to take effect...
Starting zebra and bgpd on R1
Starting zebra and bgpd on R2
Starting zebra and bgpd on R3
Starting web servers
*** Starting CLI:

Step 2 : does not work. (opened in a new terminal)

mininet@mininet-vm:~/bgp$ sudo ./connect.sh 
Connecting to R1 shell
node `R1' not found

Can you please help me find the problem?

Thanks,
Ron

**Comment by jvimal** [comment]
@rnilekani Could you try the lab on this VM: http://www.scs.stanford.edu/~jvimal/mininet-sigcomm14/mininet-tutorial-vm-64bit.zip?

It's the exact environment we used for the SIGCOMM demo.  It's likely that I relied on features that don't work anymore.  Please give it a try and let us know.

**Comment by rnilekani** [comment]
Thanks for responding @jvimal. I shall test the code tonight and provide the feedback tomorrow morning.

**Comment by rnilekani** [comment]
@jvimal , It worked on the SIGCOMM VM. Thank you. Although, I am curious to find why it doesnt work on mininet VM.

**Comment by jvimal** [comment]
Thanks for the update @rnilekani.  I am not sure why.  I might take a look sometime, but it's low on my priority.  It's likely that some API with Linux/Mininet has changed.  For now, let me update the steps on the Wiki to point to the the VM above so others don't face the same issue.

**Comment by jvimal** [comment]
I've updated the Wiki with new instructions so .  I'll close this issue as "will fix later."

@lantz -- OK to close this issue?

**Comment by rnilekani** [comment]
Thanks  @jvimal

**Comment by thrownullpointer** [comment]
Can someone post the output of mininet> dump? While running it against the working image?

**Comment by rnilekani** [comment]
@jvimal, Please find the screenshots below. Let me know if you need anything else. 

https://github.com/mininet/mininet/wiki/BGP-Path-Hijacking-Attack-Demo
![11](https://cloud.githubusercontent.com/assets/6173303/9051993/7066b08a-3a27-11e5-8e0a-8dafed38a2b5.png)
![12](https://cloud.githubusercontent.com/assets/6173303/9051995/74b3b3f4-3a27-11e5-98f7-ce9b2d386be2.png)

**Comment by rnilekani** [comment]
Please find the screenshots attached.

Thanks,
Ron

On Mon, Aug 3, 2015 at 8:59 PM, thrownullpointer <notifications@github.com>
wrote:

> Can someone post the output of mininet> dump? While running it against the
> working image?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mininet/mininet/issues/535#issuecomment-127455177>.
>



-- 
Ron Nilekani
Network Security Operations
Rackspace

**Comment by thrownullpointer** [comment]
Not showing up for me :( the text would be just as good

**Comment by dearzubi** [comment]
Hi,

I have fixed the issue and updated the code on this repository:

[https://github.com/dearzubi/bgp](https://github.com/dearzubi/bgp)
