### ISSUE TITLE
Mininet OVF not working, converted OVF>VMS not working

### ISSUE THREAD

**Issue by JaapLaaij** [mininet/mininet#564]
Hi,

I deployed the Mininet OVF in Esxi v6.0.
Deployment gives no option to change te preconfigured static address to dhco e.g.
Power on results in the vnic looking for something to boot from.
Next attempt was after converting the ovf to vmx and import it in Esxi.
Power on resulted in error message:
Failed to open disk scsi0:0: Unsupported or invalid disk type 7. Ensure that the disk has been imported.

Any ideas?

Thanx Jaap

**Comment by lantz** [comment]
This doesn't sound like a Mininet bug but a user error of not importing the vmdk as recommended in the documentation.

**Comment by lantz** [comment]
Closing because of no followup. Reopen if it is still an issue.
