### ISSUE TITLE
/sys mounts outlive mininet execution

### ISSUE THREAD

**Issue by thinred** [mininet/mininet#565]
Hi,
the mounts done in namespaces outlive the execution of mn. It results with many /sys mounts polluting the system after a few executions of mininet. This was reported in Debian: https://bugs.debian.org/799654

The problem is due to systemd changing the default semantics of mounts (which are shared). The fix is to make the mounts done by mnexec local to the containers. Here is a fix that we apply in Debian currently: https://anonscm.debian.org/cgit/collab-maint/mininet.git/tree/debian/patches/0001-mnexec-properly-setup-the-mount-namespace.patch?id=015854c68385282fb0a1b0e8f05cd45510d32063

Cheers,
Tomasz

**Comment by lantz** [comment]
This is an irritating development, but the same issue has cropped up on Fedora. I think the fix looks good.

**Comment by thinred** [comment]
I agree. Although most of systemd stuff is really cool and fancy, some invasive changes break lots of stuff. It seems that this is the price of evolution.
