### ISSUE TITLE
A little help with hosts

### ISSUE THREAD

**Issue by Hesam-Naderi-Dehkordi** [mininet/mininet#567]
Hi everybody. I know that my question isn't neither a bug nor an issue but I didn't know any better place for asking my question.
Could anyone help me in adding one more interfaces to one of my virtual hosts?
I want that one of my virtual hosts (not important in which topology , tree , linear,....) have 2 interfaces connected to the ovs switch?
How it can be overcame by using the terminals of virtual hosts (xterm) and the terminal of base system hosting mininet and openvswitch. (for example using ip , ushare and other commands)

I will be so thankful if anybody can direct me with this approach (because I'm a newbie to python, very low knowledge in this programming language)  but if there isn't such way , any other ways by using mininet's API's and others are welcomed too.

So many thanks.

**Comment by lantz** [comment]
Please don't abuse github issues for random questions.

Since you seem to have found the project page (https://github.com/mininet/mininet) please note that a) there's README text and b) there's also a link to our web site.

**Comment by Hesam-Naderi-Dehkordi** [comment]
Abuse? Random question?!

I could ask my question in a way so it look like a feature request for host with two links. So I don't know why it's a random question!
Your answer didn't even direct me in a good place to look or ask for my question.
So you tell me to read all the pages related to mininet whole days and maybe finally maybe get two lines of my simple answer.

Just closing the issue isn't a warm welcome to the community
