### ISSUE TITLE
Mininet simulation with data center topology construction problem?

### ISSUE THREAD

**Issue by nckustudent** [mininet/mininet#576]
Hello!
We are using mininet simulator to simulate data center network environment.
Our equipment is VMWare 5.1 version, eight cpus and 200GB memory.
But the problem is when we simulate 1024 hosts 320 switches and 1280 links, mininet execute net.build() to built link that need to use too much time. It use around 4 to 8 hours.However, we use "top" command to see how mininet works, it only use about 8GB memory but the environment has 200GB memory. I've got a question that if we simulate data center network in large memory size, the speed of mininet doesn't go up?
How cloud I make mininet topology construction go fast?

**Comment by pichuang** [comment]
Maybe you can try use Mininet Cluster Edition. Use more computer to do your experimental.

**Comment by lantz** [comment]
Please submit questions to the mailing list, thanks!

Also it shouldn't take that long - either something is wrong with your environment or possibly you are not using the latest version of mininet - please update to current master branch.
