### ISSUE TITLE
missing proc files

### ISSUE THREAD

**Issue by black0027** [mininet/mininet#579]
I am testing mptcp in mininet. I am using mptcp linux kernel v0.89.
in my test, I want to set some host to use mptcp, and other host to use legacy-tcp.

but in mininet host terminal, proc file "/proc/sys/net/mptcp/mptcp_enabled" is missing, even though my real linux host has proc file "/proc/sys/net/mptcp/mptcp_enabled".

is there anyone who can help me?

**Comment by lantz** [comment]
Please don't abuse github issues for questions that belong on the mailing list, thanks!

**Comment by Heath68** [comment]
Same problem，have you fixed it?
