### ISSUE TITLE
Using Mininet to do analytical models of different types of network topologies

### ISSUE THREAD

**Issue by evelinad** [mininet/mininet#616]
I have a set of analytical models of the execution time from some MPI applications that I try to validate against real measurements on different network topologies.
However, I don't have real systems for all the topologies that I want to model.

I tried to use Mininet since it allows the simulation of different types of toplogies.

When comparing the execution times between Mininet and a real hardware network topology, I noticed that the execution time of the MPI applications is several times lower in Mininet.

Is it possible to use Mininet for what I am trying to achieve ?
I posted on the mailing list more details about my performance measurements [1]

Thanks !

[1]
https://mailman.stanford.edu/pipermail/mininet-discuss/2016-April/006838.html

**Comment by lantz** [comment]
This is not a bug or feature request.
