### ISSUE TITLE
save topology

### ISSUE THREAD

**Issue by hkati** [mininet/mininet#620]
Hello guys,
I started my topology with this command: sudo mn , after that , I'm adding some new hosts,switches etc, and I want to save it.
How can I do it (without using API)?

Thanks

**Comment by lantz** [comment]
I'm not aware of CLI commands (besides calling the Python API) to add devices to a network.

It seems as if you are asking for a new feature, a topology file dump command. Maybe you can articulate how you think it should work.

**Comment by hkati** [comment]
Hello,
I'm a newer in Mininet commands , I search if it's possible to save my own topology using CLI commands.
Look this picture:
<a href="http://s1360.photobucket.com/user/HKati/media/Capture%20drsquoeacutecran%202016-04-23%20agrave%2007.08.02_zpsiw7ainws.png.html" target="_blank"><img src="http://i1360.photobucket.com/albums/r653/HKati/Capture%20drsquoeacutecran%202016-04-23%20agrave%2007.08.02_zpsiw7ainws.png" border="0" alt=" photo Capture drsquoeacutecran 2016-04-23 agrave 07.08.02_zpsiw7ainws.png"/></a>
I ask ,is Mininet can save topologies using this method?
For example, if I make "exit" can I find this topology somewhere in cache or another file?

**Comment by dmolavi** [comment]
In the "examples" directory, there is the miniedit.py file. Run that, create your topology and it can be exported as a python file to edit further.

**Comment by lantz** [comment]
Please don't abuse github issues by submitting random questions that are not bug reports or feature requests.
