### ISSUE TITLE
Failed to enable slicing in user switch (ofsoftswitch13) in mininet2.3.0d1

### ISSUE THREAD

**Issue by DavinciFan** [mininet/mininet#628]
Hi all,
  I use mininet to make the experiment and I want to add the queue to the port of the switch which is the **ofsoftswitch13**. When I use "**sudo dpctl unix:/tmp/s1 queue-mod 1 1 80**" to add the queue, there is a error.
```
RECEIVED (xid=0xF0FF00F0):
error{type="QUEUE_OP_FAILED", code="EPERM", dlen="56"}
```
  I find a answer(http://stackoverflow.com/questions/33677006/adding-queues-to-switch-of-ofsoftswitch13-implementation-doesnt-work?answertab=active#tab-top) for this problem. Because of mininet set the user switch "--no-slicing", failing to add the queue. Then I follow the answer to modify the mininet, but it doesn't work and the switch can't negotiate with floodlight controller.
```
May 14 06:36:10|00001|vconn_unix|ERR|/tmp/vconn-unix.23705.0: connection to /tmp/s1 failed: No such file or directory
dpctl: Error connecting to switch unix:/tmp/s1. (No such file or directory)
```
  I don't know how solve it, please help me?

**Comment by sharleengo** [comment]
Hello, did you find a solution to your problem? I'm currently experiencing the same issue
