### ISSUE TITLE
Can't download VM images, downloads.mininet.org is down or link is wrong.

### ISSUE THREAD

**Issue by ast** [mininet/mininet#631]

**Comment by sathishakula** [comment]
https://github.com/mininet/mininet/wiki/Mininet-VM-Images You can get it from here

**Comment by lantz** [comment]
Works fine for me - closing.

**Comment by char7811** [comment]
Any of the links are working :( https://github.com/mininet/mininet/wiki/Mininet-VM-Images

**Comment by lantz** [comment]
Seems to be working fine.
