### ISSUE TITLE
Encrypt destination IP

### ISSUE THREAD

**Issue by sathishakula** [mininet/mininet#639]
I want to encrypt the ip address of the destination as in i dont want others to know my destination ip when they run a wire shark on one of my routers instead it should be replaced with the router ip itself and the destination ip should be encrypted .

**Comment by lantz** [comment]
This sounds like a feature request for a software switch, not for Mininet. Mininet uses existing software switches. What you are describing sounds like an Ethane switch, so you might want to look at that work.
Closing.
