### ISSUE TITLE
Run a python Function by command in mininet CLI

### ISSUE THREAD

**Issue by hmd1st** [mininet/mininet#657]
I need to run a python function that I have besides my main function in mininet cli.
let me illustrate what I need exactly. consider a network script like this:

#!/usr/bin/python
from mininet.net import Mininet
from mininet.node import Controller, RemoteController
from mininet.node import Host, Node
from mininet.node import OVSKernelSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.link import TCLink, Intf

def myFunc():
    print "Hello Mininet...!!!"
def myNetwork():
    net = Mininet( topo=None,
                   build=False,
                   ipBase='10.0.0.0/8')
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch, failMode='standalone')
    h2 = net.addHost('h2', cls=Host, ip='10.0.0.2', defaultRoute=None)
    h1 = net.addHost('h1', cls=Host, ip='10.0.0.1', defaultRoute=None)
    s1h1 = {'bw':10000}
    net.addLink(s1, h1, cls=TCLink , **s1h1)
    s1h2 = {'bw':100}
    net.addLink(s1, h2, cls=TCLink , **s1h2)
    net.build()
    for controller in net.controllers:
        controller.start()
    net.get('s1').start([])
    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

I need to invoke myFunc() from mininet CLI, like this:
mininet>myFunc

**Comment by lantz** [comment]
Please don't abuse the github issue system for random questions. :(
Please read the documentation.
