### ISSUE TITLE
Mininet VM image not booting in VirtualBox 5.1.4 on Windows 8.1

### ISSUE THREAD

**Issue by s6k1992** [mininet/mininet#660]
Hi ,
Myself Sreejit Menon and i am completely new to linux systems .I am trying
to install the Mininet 2.2.1 on Ubuntu 14.04 LTS - 32 bit  using the
mininet VM image provided from mininet.org site using virtual box 5.1.4.But it
seems my VM doesn't start properly and gets stuck just after 3-4 seconds.I
am using windows 8.1 64-bit system.I have attached the snapshot here.
Can anyone guide why I am getting stuck and how to solve it?
Your kind help is really appreciated.
![screenshot](https://cloud.githubusercontent.com/assets/21205849/17909667/4e67d7fa-693a-11e6-8a14-d11cf8dfcbd1.jpg)

**Comment by lantz** [comment]
Can you please confirm that:

1. You can install and boot Ubuntu 14.04 in VirtualBox on your system?
2. You are not looking at the wrong Linux virtual console?
    https://github.com/mininet/mininet/wiki/FAQ#blank-screen

**Comment by s6k1992** [comment]
Hi Lantz,
Sorry for the late reply,was occupied in other tasks.Pleas find my answers
below in order of you questions:
1.I didn't check with Ubuntu 14.04 but i tired with Linux Mint OS 32-bit.In
virtual Box it did boot but I didn't get its GUI even after I tired all
required steps,but in Hyper-V I was able to install the same ISO image file
with success.
2.checked and tried evrything as mentioned in link but nothing working.



Now I need to bring another thing to your notice.Whenever I am extracting
the Mininet VM image i am expected to get .ovf and .vmdx file.But I am not
getting the .vmdx file instead i am getting another WinZip file of around 2
GB!

Could you suggest further actions and also why this extraction is not
giving me .vmdx file?






Appreciate your concern and quick reply!!!
Thanka And Regards,
Sreejit Menon

**Comment by lantz** [comment]
I had no problem extracting the zip file - I think there may be a problem with your system.

**Comment by s6k1992** [comment]
Hi lantz,
yes it was OS issue.I tried to install the mininet on  second OS windows 8
on same machine using VirtualBox and i succeeded.
As discussed earlier in windows 8 the zip file was extracted properly and i
could see the .vmdx file.
Thanks for your input!!!
