### ISSUE TITLE
help for adding routing table

### ISSUE THREAD

**Issue by mhafshari** [mininet/mininet#663]
hello everyone
I am trying to configure a router in Mininet and I am following the tutorial that is on this page:
 https://github.com/mininet/openflow-tutorial/wiki/Router-Exercise 
 
 But I do not know how I can put the routing table in the router, because the tutorial is the structure of the table but is not how you can configure the router with that information. I do not know how to configure ARP reply.
please help me   x:

**Comment by lantz** [comment]
Please don't abuse github issues - thanks!

p.s. You aren't thinking about the problem correctly - please think about it just as an L3 switch, then go from there.
