### ISSUE TITLE
Think about removing device entries in vm before we ship it, or using an ovf

### ISSUE THREAD

**Issue by lantz** [mininet/mininet#67]
When we create a VM, I believe the VM has random MAC addresses, but Ubuntu records those MAC addresses in its network configuration. This means that if you build a new virtualbox VM from the .vmdk it ends up with stale MAC/interface configurations.

**Comment by cheriimoya** [comment]
is this still relevant? the vm works for me

**Comment by lantz** [comment]
There may still be an issue that the VM has fixed MAC addresses, but I think we can close this for now.
