### ISSUE TITLE
OVSLink error

### ISSUE THREAD

**Issue by Tassakhi** [mininet/mininet#677]
I have installed mininet 2.1.0.
ovs-vswitchd (Open vSwitch) 1.4.6
Compiled Jun 24 2015 15:16:30
OpenFlow versions 0x1:0x1

I tried making a topology using OVSLink but it shows me this error.   

from mininet.link import OVSLink
ImportError: cannot import name OVSLink

**Comment by lantz** [comment]
Can you confirm that this error occurs with the current master branch of Mininet?

**Comment by lantz** [comment]
Closing because it seems to be a version mismatch.
