### ISSUE TITLE
# mininet package need....

### ISSUE THREAD

**Issue by farflower** [mininet/mininet#687]
hello everyone!
i install mininet on ubuntu 14.04 and 14.10 and kali 2016 but it runs incorrect. can anyone said what package or tools need for run mininet correctly or what package installed on mininet vm. the mininet vm is run very good and all command on it execute whiteout any problem but when i install mininet on kili for example some command have problem. can anyone answer ?

**Comment by lantz** [comment]
I don't understand this bug report. Could you please clarify the issue along with the exact steps required to reproduce it, the expected behavior, and the actual behavior?

**Comment by farflower** [comment]
can you say what tools installed on mininet vm because mininet vm works good. if i know that i installed all package on my ubuntu.

**Comment by lantz** [comment]
Closing this - it doesn't seem like it's a bug report or feature request.
