### ISSUE TITLE
IPv6 ping problem

### ISSUE THREAD

**Issue by pierventre** [mininet/mininet#690]
ping for ipv6 assumes addresses z/xx but this is in general not true. In ipv6 we can have also z/xxx addresses. Moreover, I suggest to move the parameters from 'v6Addr' to a more immediate 'ipv6'.

`ip, prefixLen = dest.params.get('ipv6', []).split( '/' )`
`result = node.cmd( 'ping6 -c1 %s -I %s %s' % (opts, node.intfs.get(0), ip))`

**Comment by pierventre** [comment]
my bad...QA uses a different version of Mininet

**Comment by lantz** [comment]
They really shouldn't.
