### ISSUE TITLE
mininet download link not working

### ISSUE THREAD

**Issue by shark-S** [mininet/mininet#691]
I am trying to download mininet 64-bit image but download link says "404 File not found".

**Comment by eaparker2001** [comment]
This is the link that's not working: 
http://downloads.mininet.org/mininet-2.2.1-150420-ubuntu-14.04-server-amd64.zip

**Comment by sinnerkem** [comment]
It is redirected to http://onlab.vicci.org/mininet-vm/ and resulted in access denied

**Comment by lifecrisis** [comment]
I have experienced this same problem.  I get a further error message in the form of raw XML...

```xml
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>48FF16EB9F7D03D5</RequestId><HostId>0qUcSWM8GqHAmLnLvSZ2danvaAcTRYTrryHW3s1qTFrgEvRNFACG2GfOpBqHZbAvfKvqElFHkoQ=</HostId></Error>
```

**Comment by lantz** [comment]
Ugh, our DNS provider seems to have broken URL forwarding for some reason. As a temporary workaround, I've adjusted the URLs on the VM download page.
