### ISSUE TITLE
checksums not provided on Mininet VM image download page

### ISSUE THREAD

**Issue by lifecrisis** [mininet/mininet#692]
I don't see any links to checksums that can be used to verify the integrity of the .ZIP files holding Mininet VM images.  Is this something that could be added?

The page I'm referring to can be found [here](https://github.com/mininet/mininet/wiki/Mininet-VM-Images).

**Comment by lantz** [comment]
Checksums are a good idea. Ideally they should also be hard to alter and fetched via https, but for now we can certainly add them to the download page.

**Comment by lantz** [comment]
Included with Mininet 2.2.2 and greater.
