### ISSUE TITLE
dead link to docs.mininet.org

### ISSUE THREAD

**Issue by lifecrisis** [mininet/mininet#693]
[This page](http://mininet.org/contribute/) proffers a dead link to the Mininet documentation.  I believe it should point to the wiki.

The offending link is this one:

```html
<a href="docs">docs.mininet.org</a>
```

**Comment by lantz** [comment]
The link is correct. There is a problem with the DNS
Service apparently.

**Comment by lantz** [comment]
Seems to work fine now - closing.
