### ISSUE TITLE
Consider adding a github issue template

### ISSUE THREAD

**Issue by nemethf** [mininet/mininet#696]
I often see that an issue (e.g., #695, #688, #682, #667,  #663, ...) is closed with something like "please do not abuse the github issue system for random questions."  Random questions might be an acceptable practice for other projects, so it wouldn't hurt to educate the contributors about the local rules. 

Writing an "issue template" might be a good way to explain the acceptable usage of the issue system.  See the details here: https://github.com/blog/2111-issue-and-pull-request-templates and https://help.github.com/articles/creating-an-issue-template-for-your-repository/

I'm awfully sorry if I abused the issue system with this issue.

**Comment by lantz** [comment]
It's a feature request. ;-)

**Comment by lantz** [comment]
Thanks @nemethf - added in d338b4425bd6e77b492abb566dc5f7708d506c06
Feel free to submit changes if you think they are appropriate.
