### ISSUE TITLE
Correct ordering of hosts in iperf

### ISSUE THREAD

**Issue by arnavkagrawal** [mininet/mininet#719]
### Expected/Desired Behavior:
The iperf function should create a connection from client to server.
The function document expects hosts to be ordered as [server, client]
(assuming from the return value)

### Actual Behavior:
The function creates a connection from server to client.

**Comment by arnavkagrawal** [comment]
Sent in a pull request.
https://github.com/mininet/mininet/pull/718

**Comment by lantz** [comment]
Closing since we closed #718 for now.
