### ISSUE TITLE
Typo in the install script

### ISSUE THREAD

**Issue by percyperezdante** [mininet/mininet#721]
Hi
Apologize if this is not the correct place to post this, but it seems there is a typo in the install.sh script which give the below error.  

### Expected/Desired Behavior:
Line 186:   
 \-  git clone git://github.com/mininet/openflow
\+ git clone https://github.com/mininet/openflow.git

### Actual Behavior:
-8---
$ git clone git://github.com/mininet/openflow
Cloning into 'openflow'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection refused
github.com[1: 192.30.253.112]: errno=Connection refused
-8---

### Detailed Steps to Reproduce the Behavior:
./util/install.sh -nfv

### Additional Information:
The above modification worked for me. In the end, and if it  is correct,  it would seem like the best advice to change it.

**Comment by lantz** [comment]
The `Connection refused` error you describe has nothing to do with the URL format.
```
$ git clone git://github.com/mininet/openflow
Cloning into 'openflow'...
remote: Counting objects: 12217, done.
remote: Total 12217 (delta 0), reused 0 (delta 0), pack-reused 12217
Receiving objects: 100% (12217/12217), 8.49 MiB | 9.26 MiB/s, done.
Resolving deltas: 100% (8312/8312), done.
Checking connectivity... done.
```
Closing since this seems to be a connectivity issue rather than a URL format error.
