### ISSUE TITLE
My computer boots on the mininet vm

### ISSUE THREAD

**Issue by picsou58** [mininet/mininet#722]
Please help me, this is very urgent
I installed mininet but have no experience nor understanding of how VM's work and now my computer boots on the mininet vm by default .
My cmd prompt is now "username@mininet-vm:" instead of the regular one, i can't access most of the linux cmds and i am afraid that it may pose a serious security threat.
I need to revert back and i don't know how, please help. Send help at tom.barat@telecomnancy.net please.
i am using Lubuntu
Thank you for your time

**Comment by lantz** [comment]
I suspect this is a user error where you might have run the Mininet VM install script by mistake (we don't recommend this and `install.sh -a` doesn't change the hostname.)  Closing.
