### ISSUE TITLE
ImportError: cannot import name OVSIntf

### ISSUE THREAD

**Issue by Wasdns** [mininet/mininet#723]
Hi, all.

I tried to rewrite the class `OVSSwitch` in the file `mininet/node.py` in order to enable p4 features based on OvS. 

I didn't change the method `intfOpts` that used the `OVSIntf`:

```
    def intfOpts( self, intf ):
        "Return OVS interface options for intf"
        opts = ''
        if not self.isOldOVS():
            # ofport_request is not supported on old OVS
            opts += ' ofport_request=%s' % self.ports[ intf ]
            # Patch ports don't work well with old OVS
            if isinstance( intf, OVSIntf ):
                intf1, intf2 = intf.link.intf1, intf.link.intf2
                peer = intf1 if intf1 != intf else intf2
                opts += ' type=patch options:peer=%s' % peer
        return '' if not opts else ' -- set Interface %s' % intf + opts
```

### Expected/Desired Behavior:

Start the mininet successfully.

### Actual Behavior:

However, it raised the exception:

```
root@ubuntu:/home/wasdns/demo# ./run_demo.sh 
parsing successful
semantic checking successful
Header type standard_metadata_t not byte-aligned, adding padding
Generating json output to /home/wasdns/demo/slices_demo5.json
Traceback (most recent call last):
  File "topo.py", line 9, in <module>
    from p4ovs_mininet import P4OvS, P4Host
  File "/home/wasdns/demo/p4ovs_mininet.py", line 13, in <module>
    from mininet.link import Link, Intf, TCIntf, OVSIntf
ImportError: cannot import name OVSIntf
```

### Detailed Steps to Reproduce the Behavior:

1.I writed the class `P4OvS` based on [p4_mininet](https://github.com/Emil-501/p4factory/blob/master/mininet/p4_mininet.py#L49) and [node.py](https://github.com/mininet/mininet/blob/master/mininet/node.py#L860).

2.writed my `topo.py`, import the P4OvS.

3.call the `switch=P4OvS` in the `Mininet()`. 

### Additional Information:

My OS is Ubuntu 14.04 64bit.

mininet version: 2.1.0

**Thank you very much!**

Best Regards,
Wasdns.

**Comment by lantz** [comment]
This doesn't sound like a bug in Mininet. You should really not need to modify Mininet at all since you can simply subclass, and you can also use the `--custom` feature to access new classes from the `mn` command line.

Can you confirm that this issue occurs in an *unmodified* Mininet? If not, can you please close it? Thanks.

**Comment by Wasdns** [comment]
@lantz , Hi,

Thank you for your guidence! I'll try to find a better solution. 

Best Regards,
Wasdns.
