### ISSUE TITLE
cannot start switches

### ISSUE THREAD

**Issue by EdwardHXu** [mininet/mininet#726]
Mininet uses GitHub issues for bug reports and feature requests only.
These issues can be viewed at bugs.mininet.org

If you have a question that is not a bug report or a feature request,
please use the documentation at docs.mininet.org, the FAQ
at faq.mininet.org, and the mininet-discuss mailing list.

For bug reports, please fill in the following information in detail,
and also feel free to include additional information such as debug
output from mn -v debug, etc.
--- Cut Here ---
I'm new to the SDN area and I really got confused with OVS and mininet. I can start my mininet correctly on my CentOs server (install mininet on CentOs really troubles a lot...). But after one month, I forgot what I have done with OVS so that mininet cannot start switches any more. This issue really sucks me up...
￼
￼

**Comment by EdwardHXu** [comment]
Below is my OVS info:
Bridge "s1"
        Controller "ptcp:6654"
        Controller "tcp:127.0.0.1:6653"
        fail_mode: secure
        Port "s1-eth1"
            Interface "s1-eth1"
        Port "s1"
            Interface "s1"
                type: internal
        Port "s1-eth2"
            Interface "s1-eth2"
    ovs_version: "2.3.2"

I thought it was the ''s1'' bridge's problem so I deleted it which could not help. 
When I start mininet it would freeze here:
[root@VM_16_25_centos mininet]# mn
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller
c0 
*** Starting 1 switches
s1 ...

no CLI anymore... How can I solve this issue?

**Comment by lantz** [comment]
Can you confirm that this problem happens with an unmodified Mininet running in the Mininet VM? If not,  can you either close the issue or change it to something like "feature request: centOS support?"

**Comment by EdwardHXu** [comment]
thank you @lantz I've already solved this issue. I accidentally killed ovs-vswit process so mininet cannot started switches anymore... I'll close this issue

**Comment by ShikharJ** [comment]
@EdwardHXu How did you happen to restart `ovs-vswitchd`?

**Comment by nghiadanh26** [comment]
@EdwardHXu hello, I have met this issue today. Maybe I killed ovs-swit process too. But how can fix this problem? Thank you very much!

**Comment by basrahd** [comment]
I encountered this issue today. Maybe I killed the ovs-swit process too. @nghiadanh26 can you please describe how to solve this problem

**Comment by CodingLappen** [comment]
Restart the daemon guys.

**Comment by basrahd** [comment]
@CodingLappen Sir, please can you explain **how** and **why** do  Restart the daemon ?

**Comment by Namyalg** [comment]
Has anyone been able to solve this issue? The mininet CLI does not show up for me

**Comment by FusionStreak** [comment]
On Fedora 38 (should be similar on other RHEL based distros)
`systemctl start ovs-vswitchd.service`

Basically newer distros use `systemctl` rather than `service`.
