### ISSUE TITLE
pingall fails

### ISSUE THREAD

**Issue by xricj** [mininet/mininet#730]
onal information such as debug
output from mn -v debug, etc.
### Expected/Desired Behavior:
 I install mininet in ubuntu 16.04 using native isntalation from source and then I run sudo mn
### Actual Behavior:
pingall fails (after sudo mn) 
### Detailed Steps to Reproduce the Behavior
native instalation of mininet 
sudo mn
pingall ->fails

**Comment by xricj** [comment]
is there any way to undo the changes done by install.sh?

**Comment by lantz** [comment]
Travis CI shows that 16.04 works, but remember that 16.04 has a kernel bug which may cause Mininet to stop working, so we recommend using an earlier kernel or 14.04.
