### ISSUE TITLE
Why Mininet can't install OVS 2.7.0 automatically by -v at linux kernel 4.8 (Ubuntu 16.10/17.04) ?

### ISSUE THREAD

**Issue by MaoJianwei** [mininet/mininet#733]
Why Mininet can't install OVS 2.7.0 automatically by -v at linux kernel 4.8 (Ubuntu 16.10/17.04) ?

**Comment by lantz** [comment]
Please include the error output, thanks!

**Comment by MaoJianwei** [comment]
According to the required kernel version, OVS 2.7.0 can be installed. But it just 2.6.0

![qq 20170419150612](https://cloud.githubusercontent.com/assets/12800168/25167358/c93b1238-2511-11e7-9625-8718fa6e37f8.jpg)

**Comment by MaoJianwei** [comment]
that is screenshot at Ubuntu 16.10

**Comment by hwchiu** [comment]
I think the reason is that the current version of openvswitch on ubuntu package is 2.6.1 and you can find [here](http://packages.ubuntu.com/zesty/openvswitch-switch)
And the mininet will automatically use that to install OVS and that's why you will see 2.6.0.

**Comment by lantz** [comment]
Yes.

**Comment by cheriimoya** [comment]
After installing mininet with the install script, the output of `sudo ovs-vsctl show` is `ovs_version: "2.13.3"` for me, so i think this can be closed now
