### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by chenyanfun** [mininet/mininet#735]
hi：
everybody，I get a error,when I compile the code for mininet。and I have not error.but when I run "mn",I can't get true response。the following is my error：
*** Creating network
*** Adding controller
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

OSError: [Errno 8] Exec format error
--------------------------------------------------------------------------------
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller udpbwtest mnexec ivs 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller udpbwtest mnexec ivs 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapathsovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.

if I need to install nox？but I install nox and still is error。

**Comment by hwchiu** [comment]
The half part of your message seems like a "clean" step.
Do you have all command you type and all detail output?

**Comment by chenyanfun** [comment]
I according to:
1、git clone https://github.com/mininet/mininet
2、modify install.sh to standy by centos
3、mininet/util/install.sh -a to compile get all is not error 
and I can use mn command

**Comment by hwchiu** [comment]
Do you have install the OVS ?
Since the centos is not supported by the mininet by default.
Maybe you should try to use other distribution like Ubuntu and it can save your time.

**Comment by chenyanfun** [comment]
yes,I installed ovs ,maybe is the operating system's error,I'll try to use Ubuntu,Because I can't savle the problem temporarily。thanks

**Comment by lantz** [comment]
This doesn't sound like a Mininet problem, and you seem to be ignoring the actual error message from the exception! It also sounds like you are running on CentOS and have modified the installation script, so it also probably isn't a problem with mainline. If you think that there is some Mininet error, you can reopen this but please provide the detailed debug output.
