### ISSUE TITLE
Mininet ping : destination host unreachable

### ISSUE THREAD

**Issue by AlPazinou** [mininet/mininet#738]
Hi , 
I'm trying to use this topology in mininet 
    
![image](https://cloud.githubusercontent.com/assets/28145972/25554839/3bd8ee3c-2cd8-11e7-8cc4-3494b3e229c5.png)

I tried to do ( h1 ping h2 ) and it didn't work , altought they are in the same network 

all hosts are in the same 10.0.0.0/8 network 

I've also tried (pingall) and had this result : 

![image](https://cloud.githubusercontent.com/assets/28145972/25554858/ab1750d6-2cd8-11e7-9761-4e839ac89167.png)

what could be wrong in the topology script ?

**Comment by AlPazinou** [comment]
It workes now , I had to connect S2 and S4 to the controller

**Comment by wuyouke** [comment]
controller must connect to openflow switch

**Comment by christyunique** [comment]
So, for a tree topology, every openflow switch should be connected to the controller?

**Comment by jahnavi666** [comment]
can u please mention how to connect s2 and s4 to controller

**Comment by HajraAli** [comment]
can u please mention how to connect s2 and s4 to controller. I had the same problem

**Comment by BAHYAO** [comment]
me too, i face the same problem
