### ISSUE TITLE
The Queue Of AQM In The Mininet Does Not Work

### ISSUE THREAD

**Issue by pigstars** [mininet/mininet#740]
I used Mininet to do something about AQM.
First,I set the topo like this: H1 - S1 - H2
Next,I set the switch's queue like this:
```
xterm s1 >
 tc qdisc replace dev s1-eth1 root pfifo limit 1000
 tc qdisc replace dev s1-eth2 root pfifo limit 1000
```
And,I let the H1 sent packages (which exceed the bandwitch)(UDP)  to H2.

H1 PING H2 
the result showed the time always increase and I used the Wireshark can't see the package loss.

I want to see the time is steady at a high number and some ping loss.

**Comment by lantz** [comment]
This doesn't sound like a mininet error.
