### ISSUE TITLE
Pingall for a 'single' topology doesn't work.

### ISSUE THREAD

**Issue by sushmita13** [mininet/mininet#742]
### Additional Information: command passed:
sudo mn --topo single,3 --mac --controller=remote,ip=127.0.0.1,port=6633

This is the command I used to generate a single topology , but it doesn't create any network except of showing the switch.
When I tried replacing single with linear/tree it works fine.What could be the problem?
Thanks in advance :)

**Comment by hwchiu** [comment]
I copy your command and found a space between the single and 3 "single, 3".
Try to remove that space and try it again.

**Comment by sushmita13** [comment]
Sorry that was a typo here, my original command did not have any space.

**Comment by hwchiu** [comment]
ok.

Since I can't reproduce the problem in my environment, I want to collect more info to reproduce it.
Do you have tried it without the remote controller?(just --topo single,3 --mac) 
What is your operating system and mininet version?
Thanks.

**Comment by sushmita13** [comment]
I tried with just the topology and it is working fine.
OS:Linux 16.04
Mininet: 2.2.1-2
So the problem lies with the controller!
Thank you :)

**Comment by lantz** [comment]
Closing since it seems to be resolved.
