### ISSUE TITLE
Refactor Python API to PEP8-compliant names

### ISSUE THREAD

**Issue by 0x326** [mininet/mininet#761]
### Expected/Desired Behavior:
Python API should be PEP 8 complaint.  Method names should be of the form `some_name`.

### Actual Behavior:
Python API is currently Java-like.  Method names are of the form `someName`.

### Detailed Steps to Reproduce the Behavior:
Run `pylint mininet/` to see deviations from PEP 8.

### Additional Information:
Code refactor is needed.  Some items can be done automatically in [PyCharm](https://www.jetbrains.com/pycharm/download/) with its 'Reformat code' feature.

**Comment by lantz** [comment]
Mininet conforms to its own Python style, which is based on the Arista style.'

Here is the description:

https://github.com/mininet/mininet/wiki/Mininet-Python-Style

And here's the tool to convert pep8 to it:

https://github.com/mininet/mininet/blob/master/util/unpep8
