### ISSUE TITLE
Build/make codecheck is broken with updated pyflakes

### ISSUE THREAD

**Issue by lantz** [mininet/mininet#762]
### Expected/Desired Behavior:

`make codecheck` should work on Ubuntu 14.

### Actual Behavior:

`pyflakes` fails with `CLI` undefined in `bin/mn`

### Detailed Steps to Reproduce the Behavior:

`make codecheck`

### Additional Information:
`pyflakes` has apparently changed in Ubuntu 14.04 LTS.

**Comment by hwchiu** [comment]
Hi.

I have try to solve this problem and issued a pull request #757. But the travis-ci has met some random CI fail on dist=Ubuntu 14.04.

**Comment by lantz** [comment]
Fixed in b142cf32ec8d401fffc2e226e2f5d61f59be305e
