### ISSUE TITLE
Wrong URL in install.sh for install of13

### ISSUE THREAD

**Issue by morland96** [mininet/mininet#769]
If trying install CPqD by 
$./mininet/util/install.sh -n3f
An error will be occurred as fllow:
`--2017-10-18 16:56:28--  http://www.nbee.org/download/nbeesrc-feb-24-2015.zip
Resolving www.nbee.org (www.nbee.org)... 130.192.225.79
Connecting to www.nbee.org (www.nbee.org)|130.192.225.79|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-18 16:56:29 ERROR 404: Not Found.
`
That's because nbee.org no more provide thire source code in www.nbee.org. They move thier things to github which is [https://github.com/netgroup-polito/netbee.git](https://github.com/netgroup-polito/netbee.git). So please change it. 

By the way, this install.sh is very not friendly for Ubuntu 16.10, some library like libxerces-c2-dev is no more in the new version. Ofsoftswitch13 changes thier README and use new libxerces which is libxerces-c3.1.

**Comment by cheriimoya** [comment]
this is fixed i think, at least i can install the tools by using the install script
