### ISSUE TITLE
Error creating interface pair

### ISSUE THREAD

**Issue by teto** [mininet/mininet#799]
With mininet 2.2.2 on nixos, on startup I have

--- Cut Here ---
```
### Expected/Desired Behavior:
(ins)
added intf lo (0) to node s1
*** s1 : ('ifconfig', 'lo', 'up')

(ins)Error setting lo up: (ins) s1 
*** Adding links:
*** h1 : ('ip link add name h1-eth0 address a2:d8:0f:1c:ba:bf type veth peer name s1-eth1 address d2:cd:da:38:81:2f netns 18605',)
(ins)--------------------------------------------------------------------------------
Caught exception. Cleaning up...

Exception: Error creating interface pair (h1-eth0,s1-eth1): (ins) 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/6ka2nlzybf85xmcm63gkw4d8v5ri5kg4-mininet-2.2.2/bin/.mn-wrapped", line 400, in <module>
    MininetRunner()
  File "/nix/store/6ka2nlzybf85xmcm63gkw4d8v5ri5kg4-mininet-2.2.2/bin/.mn-wrapped", line 136, in __init__
    self.begin()
  File "/nix/store/6ka2nlzybf85xmcm63gkw4d8v5ri5kg4-mininet-2.2.2/bin/.mn-wrapped", line 357, in begin
    listenPort=listenPort )
  File "/nix/store/6ka2nlzybf85xmcm63gkw4d8v5ri5kg4-mininet-2.2.2/lib/python2.7/site-packages/mininet/net.py", line 172, in __init__
    self.build()
  File "/nix/store/6ka2nlzybf85xmcm63gkw4d8v5ri5kg4-mininet-2.2.2/lib/python2.7/site-packages/mininet/net.py", line 444, in build
    self.buildFromTopo( self.topo )
  File "/nix/store/6ka2nlzybf85xmcm63gkw4d8v5ri5kg4-mininet-2.2.2/lib/python2.7/site-packages/mininet/net.py", line 431, in buildFromTopo
    self.addLink( **params )
  File "/nix/store/6ka2nlzybf85xmcm63gkw4d8v5ri5kg4-mininet-2.2.2/lib/python2.7/site-packages/mininet/net.py", line 366, in addLink
    link = cls( node1, node2, **options )
  File "/nix/store/6ka2nlzybf85xmcm63gkw4d8v5ri5kg4-mininet-2.2.2/lib/python2.7/site-packages/mininet/link.py", line 449, in __init__
    node1, node2, deleteIntfs=False )
  File "/nix/store/6ka2nlzybf85xmcm63gkw4d8v5ri5kg4-mininet-2.2.2/lib/python2.7/site-packages/mininet/link.py", line 493, in makeIntfPair
    deleteIntfs=deleteIntfs )
  File "/nix/store/6ka2nlzybf85xmcm63gkw4d8v5ri5kg4-mininet-2.2.2/lib/python2.7/site-packages/mininet/util.py", line 194, in makeIntfPair
    ( intf1, intf2, cmdOutput ) )
Exception: Error creating interface pair (h1-eth0,s1-eth1): (ins) 
```
I don't find the error very explicit. Any idea ? else I might dig deeper.

### Detailed Steps to Reproduce the Behavior:
I just start `sudo mn -v debug`

**Comment by teto** [comment]
I think it's because I have no telnet server running. Could it be the reason ? I don't use the official VM, I am trying to setup it on the host so I might miss components.

**Comment by lantz** [comment]
Well, this is more of an environment error or an issue with your port, but I don't think it has anything to do with telnet. 

The message and debug output is actually telling you something extremely useful: that it is getting a (fatal) error when it tries to create the virtual interface pair using the command

    ip link add name h1-eth0 address a2:d8:0f:1c:ba:bf type veth peer name s1-eth1 address d2:cd:da:38:81:2f netns 18605

This could fail for many reasons including:

 a) your kernel wasn't compiled with network namespaces
 b) there are already interfaces with the specified names
 c) the specified namespace (process 18605) doesn't exist or has exited for some reason
 etc.

`mn -c` should clean up the interfaces and namespaces so you should be able to try again and eliminate (b).

That's the most common issue. The second most common issue on strange linux distros is (a) - in that case, you usually need to rebuild your kernel with network namespaces enabled.

It's easy to check if it's a kernel/namespace issue. Try the following:

    sudo mnexec -n ip link show

(You may have to specify the path to `mnexec` if it's not in your `sudo` path.)

The result should be:
    1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default qlen 1000
            link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00

If not, then something is wrong.

**Comment by teto** [comment]
I believe a/b/c are fine. I am concerned by the fact that checks are done on the output:

```
    if addr1 is None and addr2 is None:
        cmdOutput = runCmd( 'ip link add name %s '
                            'type veth peer name %s '
                            'netns %s' % ( intf1, intf2, netns ) )
    else:
        cmdOutput = runCmd( 'ip link add name %s '
                            'address %s '
                            'type veth peer name %s '
                            'address %s '
                            'netns %s' %
                            (  intf1, addr1, intf2, addr2, netns ) )
    if cmdOutput:
        raise Exception( "Error creating interface pair (%s,%s): %s " %
                         ( intf1, intf2, cmdOutput ) )

```
and that in my case the output "cmdOutput" contains "(ins)" which is not part of sthg returned by the ip command but rather by GNU readline. I have in my ~/.inputrc `set vi-ins-mode-string` which shows the vi mode in the shell. I find it strange that it got captured by mininet but maybe the output should be checked against a regex before declaring an error instead of just ` if cmdOutput: ... error`
I tried disabling the readline setting to no avail, There is still some space emitted. I will try to add some regex checking.

**Comment by lantz** [comment]
Oh wait, somehow I managed to miss that, and it was right in the error message! Haha!

That's interesting - but `.inputrc` shouldn't affect `bash` - should it?

If there's extra output from `bash`, everything will break unfortunately.

**Comment by teto** [comment]
I just quickly glimpsed at the code, am I correct in assuming that - in a default/stock environment - `makeIntfPair` calls node.cmd -> node.sendCmd -> .. -> startShell -> m (much guessing, especially after `sendCmd`) ? I can try to add if --noediting solves anything if you an recommand me where.
It is possible that the shebangs were false `#!/bin/bash` (nixos not having a /bin folder )

Can you confirm please that the startup error is of no consequence to our problem ?
```
/run/current-system/sw/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6653',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
```

**Comment by lantz** [comment]
Kind of orthogonal - `telnet` is simply a way for `Controller.checkListening()` to determine if it can open up a TCP connection to the OpenFlow port(s) at the controller's IP address (in this case via the loopback address); if so, it assumes that the controller is reachable, has started up, and is listening for incoming connections. `m` is a separate shell script used to attach to a mininet host and possibly run commands on it. It probably makes sense to follow up on the mailing list instead so that other folks can chime in and also benefit from the discussion.

**Comment by teto** [comment]
Interestingly, while trying to debug, I ran the command form a `nix-shell` (kind of a barebone bash) and the command succeeded so there does seem to be some configuration issue.
`--noediting` shouldn't be needed if the shell is run in non interactive mode. is it ?

I am trying to look at what I must package while fixing this bug. According to INSTALL/install.sh, `fnv` flags are enough to make a barebone script work right ?
```
   To install Mininet itself, the OpenFlow reference implementation, and
   Open vSwitch, you may use:

        util/install.sh -fnv
```
I kinda like GH ui but I can go on the list if you prefer.

**Comment by teto** [comment]
Hum seems like I was wrong and there is sthg else going on

the `ifconfig lo up` fails because for some reason it returns some output
```
added intf lo (0) to node s1
*** s1 : ('ifconfig', 'lo', 'up')
sendCmd: ifconfig lo up
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Bcast:0.0.0.0  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:56 errors:0 dropped:0 overruns:0 frame:0
          TX packets:56 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4008  TX bytes:4008

```
If I run `sudo ifconfig lo up` in a terminal, it returns no output (as expected by mininet).

When I start a shell like mininet does, I get errors too:
```
LANG=C mnexec -cd env PS1= bash --norc --noediting --noprofile -is mininet:c0

[root@jedha:/home/teto]# bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```
(may be related to https://github.com/mininet/mininet/issues/712) so I wonder if the can be linked.

**Comment by teto** [comment]
Sorry for the noise, I found the reason. I apparently have 2 ifconfig, one from inetutils and one from ifconfig, they apparently don't react similarly, since for the same command one prints the output and the other not.

```
teto@jedha> sudo
/nix/store/cxv9ajjdmijdas5vjp99nspp3ycqbzpz-inetutils-1.9.4/bin/ifconfig
lo up
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Bcast:0.0.0.0  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3041 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3041 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:165988  TX bytes:165988

teto@jedha> sudo ifconfig lo up
teto@jedha> readlink -f $(which ifconfig)
/nix/store/g2jjk11fx677cqh06ljw05iizd0isjr8-net-tools-1.60_p20170221182432/bin/ifconfig
```
