### ISSUE TITLE
flawed checks for controllers

### ISSUE THREAD

**Issue by teto** [mininet/mininet#814]
While trying to package mininet, I was puzzled by the fact that I couldn't connect to the controller.
what I found out is that mininet thought it had correctly launched a controller that is not even installed.

I see 2 issues here:
- mininet doesn't seem to check if the controller was launched correctly https://github.com/mininet/mininet/blob/34b1f4161ab7cd8ce5d7c2a04a24dac8533378d9/mininet/node.py#L1406
- the test for different controllers seems uneffective, for instance https://github.com/mininet/mininet/blob/34b1f4161ab7cd8ce5d7c2a04a24dac8533378d9/mininet/node.py#L1444

### Expected/Desired Behavior:
- correctly find available controllers

### Actual Behavior:
the Controller .isAvailable member always return true I think ?!

```
def quietRun( cmd, **kwargs ):
    "Run a command and return merged stdout and stderr"
    return errRun( cmd, stderr=STDOUT, **kwargs )[0]

```
since stderr is redirected to stdout, it always returns something so for instance in my setup, I have ovs-testcontroller installed but it is never reached because previous isAvailable calls "succeed":
```
    @classmethod
    def isAvailable( cls ):
        return ( quietRun( 'which ovs-controller' ) or
                 quietRun( 'which test-controller' ) or
                 quietRun( 'which ovs-testcontroller' ) ).strip()
```

which returns sthg
```
$ which toto 
toto not found
```
so mininet ends up starting an erronous binary path as for instance:
```
*** Starting controller
c0 *** errRun: ['which', 'which:', 'no', 'ovs-controller', 'in', '(/nix/store/z8v6j7pkfi4zly0c38rjn1cjvr88l1b0-which-2.21/bin:/home/teto/rofi-scripts:/home/teto/buku_run:/home/teto/bin:/run/wrappers/bin:/home/teto/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/etc/profiles/per-user/teto/bin)'] 
which: no which: in (/nix/store/z8v6j7pkfi4zly0c38rjn1cjvr88l1b0-which-2.21/bin:/home/teto/rofi-scripts:/home/teto/buku_run:/home/teto/bin:/run/wrappers/bin:/home/teto/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/etc/profiles/per-user/teto/bin)
which: no no in (/nix/store/z8v6j7pkfi4zly0c38rjn1cjvr88l1b0-which-2.21/bin:/home/teto/rofi-scripts:/home/teto/buku_run:/home/teto/bin:/run/wrappers/bin:/home/teto/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/etc/profiles/per-user/teto/bin)
which: no ovs-controller in (/nix/store/z8v6j7pkfi4zly0c38rjn1cjvr88l1b0-which-2.21/bin:/home/teto/rofi-scripts:/home/teto/buku_run:/home/teto/bin:/run/wrappers/bin:/home/teto/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/etc/profiles/per-user/teto/bin)
which: no in in (/nix/store/z8v6j7pkfi4zly0c38rjn1cjvr88l1b0-which-2.21/bin:/home/teto/rofi-scripts:/home/teto/buku_run:/home/teto/bin:/run/wrappers/bin:/home/teto/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/etc/profiles/per-user/teto/bin)
which: no bin) in (./(/nix/store/z8v6j7pkfi4zly0c38rjn1cjvr88l1b0-which-2.21/bin:/home/teto/rofi-scripts:/home/teto/buku_run:/home/teto/bin:/run/wrappers/bin:/home/teto/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/etc/profiles/per-user/teto)
  5*** c0 : ('which: no ovs-controller in (/nix/store/z8v6j7pkfi4zly0c38rjn1cjvr88l1b0-which-2.21/bin:/home/teto/rofi-scripts:/home/teto/buku_run:/home/teto/bin:/run/wrappers/bin:/home/teto/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/etc/profiles/per-user/teto/bin) -v ptcp:6653 1>/tmp/c0.log 2>/tmp/c0.log &',)
```
I believe the isAvailaible call should check for the return value of which calls instead.

### Additional Information:
with master

**Comment by lantz** [comment]
Interesting. Well, to its credit, I note that Mininet has traditionally been packaged with one of those controllers.

Yeah, I think maybe checking the exit code might be a good idea.

**Comment by teto** [comment]
I guess that's why no one noticed the bug, everyone is using the VM.
Otherwise it's a pretty easy to trigger bug. Do you want me to send a patch
or do your prefer to fix it yourself ?

2018-07-10 15:00 GMT+09:00 lantz <notifications@github.com>:

**Comment by teto** [comment]
fixed with the merge
