### ISSUE TITLE
Malware Analysis using Mininet

### ISSUE THREAD

**Issue by saxenakanishk** [mininet/mininet#816]
I wanted to ask whether we can do malware analysis using Mininet and Wireshark.I did the same analysis using cuckoo sandbox in which I used VirtualBox. And I know that mininet also uses VirtualBox in its setup. So how can I send infected the files to all the hosts and analyze malware behaviour using Wireshark?

**Comment by lantz** [comment]
Please use the mailing list for general questions and issues for bug reports, thanks!

**Comment by saxenakanishk** [comment]
@lantz When I tried to use the mailing list I got such a response -
"You are not allowed to post to this mailing list, and your message has
been automatically rejected.  If you think that your messages are
being rejected in error, contact the mailing list owner at
mininet-discuss-owner@lists.stanford.edu."

**Comment by lantz** [comment]
1. You need to join the list before you can post. 
2. If you have a concrete api suggestion, please open up a new issue or pull request.
