### ISSUE TITLE
Pingpair command renames tested nodes in the output

### ISSUE THREAD

**Issue by xbrakl** [mininet/mininet#820]
In the last version 2.3.0d3, command pingpair renames tested nodes to incorrect names on the output.

Example output of pingpair command:

root@sandbox:~# mn
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller
c0 
*** Starting 1 switches
s1 ...
*** Starting CLI:
mininet> pingpair h2 s1
h1 -> h2 
h2 -> h1 
*** Results: 0% dropped (2/2 received)
mininet> pingpair h2 c0
h1 -> h2 
h2 -> h1 
*** Results: 0% dropped (2/2 received)
mininet> pingpair h1 c0
h1 -> h2 
h2 -> h1 
*** Results: 0% dropped (2/2 received)

**Comment by lantz** [comment]
Are you sure that pingpair takes arguments?

```mininet> help pingpair
Ping between first two hosts, useful for testing.
```

http://mininet.org/api/classmininet_1_1net_1_1Mininet.html#a1abd162ba9a3304dd091a2edda1cc4c1

**Comment by xbrakl** [comment]
Aah sorry, I missunderstood the meaning of this command. This is useless issue.
