### ISSUE TITLE
Custom topologies in examples are using probably the old way of building topos

### ISSUE THREAD

**Issue by xbrakl** [mininet/mininet#825]
Hello,

I studied how to use Python API to make a custom topology. 

The main study material to me was:
[1] https://github.com/mininet/mininet/wiki/Introduction-to-Mininet#creating-topologies
and Python API docs:
[2] http://mininet.org/api/classmininet_1_1topo_1_1Topo.html

[1] recommends to use overriding of the method `build()` when you want to make a custom topology for Mininet ver. 2.2 and above. 
[2] says the same thing in documentation of the method `build()`. Let's call this as "new API".

I found the usage of the old API in several files in folder mininet/examples in the master branch. These files uses method `__init__()` instead of `build()` to build a custom topology. I consider this as confusing and it should be fixed.

---

Lets take the custom topology as an example. 
https://github.com/mininet/mininet/blob/1969669f510a7443f58b27b1640884b06b6867d4/custom/topo-2sw-2host.py#L16-L20

I understood new API, so that line 16 should be replaced by `def build(self):` and line 20 should be deleted. Am I right? If so, then there are more files with this "mistake":

https://github.com/mininet/mininet/blob/dfb297901fd4bf0ad0cad317973180392dafa277/examples/multilink.py#L21-L25

https://github.com/mininet/mininet/blob/dfb297901fd4bf0ad0cad317973180392dafa277/examples/natnet.py#L28-L31

https://github.com/mininet/mininet/blob/dfb297901fd4bf0ad0cad317973180392dafa277/examples/linearbandwidth.py#L38-L44

Mininet walktrough on the main page is incosistant as well with the [1]. It uses code from the first custom topology example.
http://mininet.org/walkthrough/#custom-topologies

---

By the time, build-in Torus and Tree topologies are using new API. And that is right.

https://github.com/mininet/mininet/blob/dfb297901fd4bf0ad0cad317973180392dafa277/mininet/topolib.py#L9-L12

https://github.com/mininet/mininet/blob/dfb297901fd4bf0ad0cad317973180392dafa277/mininet/topolib.py#L41-L51

**Comment by gabay** [comment]
Seems correct, Created a pull request for it here: #852

**Comment by lantz** [comment]
Thanks, fixed in #852
