### ISSUE TITLE
Connect Mininet and Snort

### ISSUE THREAD

**Issue by ngthtung** [mininet/mininet#828]
Hello everyone,

I have a mininet, a controller ( floodlight ), a IDS ( Snort )
How can I connect mininet to Controller and IDS ?

I can connect mininet to Controller by :

> --controller=remote,ip=<controller's ip> port=<controller's port> 

but I still dont know how connect between mininet and IDS

Thank You.

**Comment by lantz** [comment]
not a bug report - closing
