### ISSUE TITLE
file-descriptors remain open when stop() is called

### ISSUE THREAD

**Issue by cw299** [mininet/mininet#838]
Mininet does not close all file descriptors if it is stopped by function `Mininet.stop()`. This is because the pipes of the Pseduo-TTY remain open when the network shuts down. Implementation of `Node.startShell()` opens these pipes, but they are not closed when the network is stopped:
```
        self.master, self.slave = pty.openpty()
        self.shell = self._popen( cmd, stdin=self.slave, stdout=self.slave, stderr=self.slave,
                                  close_fds=False )
        self.stdin = os.fdopen( self.master, 'rw' )
```

A possible solution for this bug could be an extension of `Node.cleanup()`:

```
def cleanup( self ):
        self.shell = None 

        """close pipes of shell"""
        if self.master: 
            os.close(self.master)
            self.master = None
        if self.slave: 
            os.close(self.slave)
            self.slave = None
```

**Comment by lantz** [comment]
Can you confirm that it is still a problem in master?

**Comment by cw299** [comment]
The problem is actually not the master, but `stdin` When both `slave` and `stdin` are closed, it works:

```
def cleanup( self ):
        self.shell = None 

        """close pipes of shell"""
        if self.slave: 
            os.close(self.slave)
            self.slave = None
        self.stdin.close()
```

**Comment by lantz** [comment]
Uh... isn’t the issue fixed in the current master *branch* of the mininet GitHub code repository?

**Comment by cw299** [comment]
You are right, it is already fixed in _master branch_. I used _apt-get_ to install mininet - this refers not to the newest version.

**Comment by lantz** [comment]
closing - fixed in master
