### ISSUE TITLE
git clone git@bitbucket.org:jvimal/bgp.git - Permission denied

### ISSUE THREAD

**Issue by evandrix** [mininet/mininet#842]
```
$ git clone git@bitbucket.org:jvimal/bgp.git
Cloning into 'bgp'...
Warning: Permanently added 'bitbucket.org' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

should really be $ `git clone --recursive https://bitbucket.org/jvimal/bgp.git`

**Comment by cheriimoya** [comment]
how does this repository affect https://bitbucket.org/jvimal/bgp?

you should probably open an issue there i guess...

this can be closed

**Comment by levita78** [comment]
Hello, I'm having trouble cloning a Jvimal folder onto my Mininet virtual machine. I'm getting this error. What should I do?
$ git clone git@bitbucket.org:jvimal/bgp.git
Cloning into 'bgp'...
Warning: Permanently added 'bitbucket.org' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please reply quickly as I have a project due this Thursday.

Thank you.
Levita

**Comment by Toni-J** [comment]
Unsubscribe please. On 7 Jan 2026, at 07:58, levita78 ***@***.***> wrote:﻿levita78 left a comment (mininet/mininet#842)
Hello, I'm having trouble cloning a Jvimal folder onto my Mininet virtual machine. I'm getting this error. What should I do?
$ git clone ***@***.***:jvimal/bgp.git
Cloning into 'bgp'...
Warning: Permanently added 'bitbucket.org' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Please reply quickly as I have a project due this Thursday.
Thank you.
Levita
