### ISSUE TITLE
h1 cannot ping h2 

### ISSUE THREAD

**Issue by odonovanmary** [mininet/mininet#849]
from mininet.net import Mininet
from mininet.node import Controller, RemoteController, OVSController
from mininet.node import CPULimitedHost, Host, Node
from mininet.node import OVSKernelSwitch, UserSwitch
from mininet.node import IVSSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.link import TCLink, Intf
from subprocess import call

def myNetwork():

    net = Mininet( topo=None,
                   build=False,
                   ipBase='10.0.0.0/8')

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',
                      controller=Controller,
                      protocol='tcp',
                      port=6633)

    info( '*** Add switches\n')
    s2 = net.addSwitch('s2', cls=OVSKernelSwitch)
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch)
    s3 = net.addSwitch('s3', cls=OVSKernelSwitch)

    info( '*** Add hosts\n')
    h1 = net.addHost('h1', cls=Host, ip='10.0.0.1', defaultRoute=None)
    h2 = net.addHost('h2', cls=Host, ip='10.0.0.2', defaultRoute=None)

    info( '*** Add links\n')
    net.addLink(h1, s1)
    net.addLink(s1, s3)
    net.addLink(s3, h2)
    net.addLink(s1, s2)
    net.addLink(s3, s2)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches\n')
    net.get('s2').start([c0])
    net.get('s1').start([c0])
    net.get('s3').start([c0])

    info( '*** Post configure switches and hosts\n')

    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )

--- Cut Here ---
### Expected/Desired Behavior:
for this script I want to be able to ping from h1 ping h2
I can ping all 3 Switches. Network and node information below 
mininet> dump
<Host h1: h1-eth0:10.0.0.1 pid=5320>
<Host h2: h2-eth0:10.0.0.2 pid=5322>
<OVSSwitch s2: lo:127.0.0.1,s2-eth1:None,s2-eth2:None pid=5309>
<OVSSwitch s1: lo:127.0.0.1,s1-eth1:None,s1-eth2:None,s1-eth3:None pid=5312>
<OVSSwitch s3: lo:127.0.0.1,s3-eth1:None,s3-eth2:None,s3-eth3:None pid=5315>
<Controller c0: 127.0.0.1:6633 pid=5301>
mininet> net
h1 h1-eth0:s1-eth1
h2 h2-eth0:s3-eth2
s2 lo:  s2-eth1:s1-eth3 s2-eth2:s3-eth3
s1 lo:  s1-eth1:h1-eth0 s1-eth2:s3-eth1 s1-eth3:s2-eth1
s3 lo:  s3-eth1:s1-eth2 s3-eth2:h2-eth0 s3-eth3:s2-eth2
c0

**Comment by yungshenglu** [comment]
I think maybe you need to add some forwarding rules in it.

**Comment by lantz** [comment]
https://github.com/mininet/mininet/wiki/FAQ#ethernet-loops

**Comment by ewre324** [comment]
> from the [FAQ](http://faq.mininet.org) https://github.com/mininet/mininet/wiki/FAQ#ethernet-loops


Thanks after spending 10 hours on the Interenet and various Ai assistants this comment helped me.
