### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by vmoiii** [mininet/mininet#853]
Hi!
I am using Ubuntu 18.04 in Virtualbox, following the instruction from http://mininet.org/download/ to install mininet from source.

I was using:
git clone git://github.com/mininet/mininet
mininet/util/install.sh -a

Then, there came an error:
error: supposed package directory 'mininet/examples' exists, but is not a directory
Makefile:50: recipe for target 'install' failed
make: *** [install] Error 1

I am wondering what does the error mean, because there is already a 'mininet/examples' existing. 
How can I fix the problem? Or, is there other way to install mininet?

**Comment by vmoiii** [comment]
> Can you confirm that this occurs with a clean install of Ubuntu 18.04?

Thanks. I installed Ubuntu 18 again and this time mininet was successfully installed.

**Comment by vmoiii** [comment]
There might be some mistake during the installation of Ubuntu.

**Comment by chenmiaojie03** [comment]
DVERSION="PYTHONPATH=. python -B bin/mn --version 2>&1" mnexec.c -o mnexec
cc: error: (most: No such file or directory
cc: error: recent: No such file or directory
cc: error: call: No such file or directory
cc: error: last):: No such file or directory
cc: error: File: No such file or directory
cc: error: "bin/mn",: No such file or directory
cc: error: line: No such file or directory
cc: error: 45,: No such file or directory
cc: error: in: No such file or directory
cc: error: : No such file or directory
cc: error: from: No such file or directory
cc: error: mininet.examples.cluster: No such file or directory
cc: error: import: No such file or directory
cc: error: (: No such file or directory
cc: error: MininetCluster,: No such file or directory
cc: error: RemoteHost,: No such file or directory
cc: error: ImportError:: No such file or directory
cc: error: No: No such file or directory
cc: error: module: No such file or directory
cc: error: named: No such file or directory
cc: error: examples.cluster": No such file or directory
Makefile:50: recipe for target 'mnexec' failed
make: *** [mnexec] Error 1
error when I run install.sh to install mininet.How to solve it.
