### ISSUE TITLE
Using TCLink in LinuxRouter example

### ISSUE THREAD

**Issue by ZhenyaKh** [mininet/mininet#854]
### Expected/Desired Behavior:
I take https://github.com/mininet/mininet/blob/master/examples/linuxrouter.py. If I add "**from mininet.link import TCLink**" and change the line 82 to "**net = Mininet( topo=topo, link=TCLink )**" when I launch the script, _pingall_ should work between all the three hosts and the router.

### Actual Behavior:

If I add "**from mininet.link import TCLink**" and change the line 82 to "**net = Mininet( topo=topo, link=TCLink )**" when I launch the script, _pingall_ works only between host h1 and the router and _dump_ command shows that the router has only one interface instead of three: 
<LinuxRouter r0: r0-eth1:192.168.1.1,r0-eth2:None,r0-eth3:None pid=6578>.

### Additional Information:

I tried to simplify the LinuxRouter example by having only two hosts and the router without any switches. But the problem is present in this simpler case too. I attach my simpler example (in Python).
[simpler_example.txt](https://github.com/mininet/mininet/files/2803815/simpler_example.txt)

**Comment by WilyWildWilly** [comment]
This issue is still present as of version 2.3.0 of Mininet. Cannot ping across two routers when link=TCLink.
