### ISSUE TITLE
ImportError: cannot import name BaseString

### ISSUE THREAD

**Issue by jaiken06** [mininet/mininet#856]
### Expected/Desired Behavior:
The import to work without errors
### Actual Behavior:
from mininet.util import ( quietRun, errRun, errFail, moveIntf, isShellBuiltin,
ImportError: cannot import name BaseString

### Detailed Steps to Reproduce the Behavior:
from mininet.topo import Topo
from mininet.net import Mininet
from mininet.util import dumpNodeConnections
from mininet.log import setLogLevel

**Comment by lantz** [comment]
Seems fine in the current master:

```
$ python <<END
from mininet.topo import Topo
from mininet.net import Mininet
from mininet.util import dumpNodeConnections
from mininet.log import setLogLevel
END
$
```

Can you confirm that this  happens after you have installed the current master branch?

**Comment by lantz** [comment]
closing as it seems to be fine in master
