### ISSUE TITLE
addLink Ordering Issue

### ISSUE THREAD

**Issue by cybronicle** [mininet/mininet#867]
In this topo, 3 routers been set up, where 2 of the routers have a switch and host behind them. The third router acts a forwarding bridge between the other 2 routers. When using addLink(), the order of the addLink call disturbs the first addLink() to r3.

### Expected/Desired Behavior:
For r1<->r3 link and r3<->r2 links to be created when using addLink()

### Actual Behavior:
Depending on order of addLink in mininet, the first link will be broken. 
Ex. r1 -> r3 and r3<->r2 
or  r1<-> r3 and r3<- r2

### Detailed Steps to Reproduce the Behavior:
Create 2 hosts and switches. Create links between each pair of host and switch. Create 3 routers. Create links between switches and routers. Create router to router links.  Create routes for inter-connectivity. Run script

### Additional Information:
help.txt attached below is the script created. help.txt originally has a .py extension. Running the script will automatically call a pingall(). After pinging, a CLI will open. From here, route commands were executed on each router. The routes will not add for the first link connection for the forwarding router. The CLI 'links' command  was executed to see if the link is properly created. Switching the order of the router addLink lines will result in a r3 full disconnect to r2 and establish full connectivity to r1's network.
 
 
[help.txt](https://github.com/mininet/mininet/files/3073640/help.txt)
 
  
  
 
![Screenshot (6)](https://user-images.githubusercontent.com/35509053/56044326-ea18df00-5d0c-11e9-98b4-f6285e6e8cd0.png)

**Comment by cybronicle** [comment]
A solution has been found. Mininet had a issue setting up public external ip addresses. To configure the link, an ifconfig to set a specific link ip on the interface was implemented.

**Comment by aporfido** [comment]
I am seeing this issue as well... What steps were taken to get around it?
