### ISSUE TITLE
Mininet doesn't add links if iproute2 is on version 5.1.0

### ISSUE THREAD

**Issue by adlerosn** [mininet/mininet#884]
### Expected/Desired Behavior:
Initialize with default topology from `$sudo mn`.

### Actual Behavior:
`$sudo mn`
few lines later...
```
*** Adding links:
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

Exception: Error creating interface pair (h1-eth0,s1-eth1): RTNETLINK answers: No such device
RTNETLINK answers: No such device
 
--------------------------------------------------------------------------------
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
```

### Detailed Steps to Reproduce the Behavior:
Just type `sudo mn` while `iproute2` is on version `5.1.0` and watch it break.

### Additional Information:
Mininet version: 2.3.0d5
Distribution: Arch Linux

### Workaround:
Downgrading `iproute2` to `5.0.0` "fixes" the error (suggested by [this forum post](https://www.linuxquestions.org/questions/linux-virtualization-and-cloud-90/mininet-iproute2-5-1-0-error-4175654108/#post5996232) and tested by me), but leaves the system outdated and potentially vulnerable.

**Comment by lantz** [comment]
Can you confirm that this problem occurs in Ubuntu 18.04 LTS?

**Comment by lantz** [comment]
Also would you like to submit a fix? ;-)

**Comment by teto** [comment]
I am on a fork of 5.1 with no problem. Could you link at iproute's issue please ?

**Comment by adlerosn** [comment]
Once I updated iproute2 from 5.1.0-1 to 5.2.0-1 from Arch repositories, @teto , mininet went back to work as if I was running it with iproute2 5.0.0-1. I just forgot to comment about it here and close this issue.
