### ISSUE TITLE
Output buffering crashes on multi-byte UTF-8 characters

### ISSUE THREAD

**Issue by benfrankel** [mininet/mininet#890]
### Expected/Desired Behavior:
Commands that output text encoded in UTF-8 should not crash mininet.

### Actual Behavior:
Mininet might crash.

### Detailed Steps to Reproduce the Behavior:
```
mininet> <host> echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXあ
```

This worked for me. You may need to add or remove Xs to get the multi-byte character (あ) in the right place, depending on how the text gets buffered.

### Additional Information:

https://github.com/mininet/mininet/blob/e203808a20e6eec9e4368757cdccce7010eab548/mininet/node.py#L237

This fails with a UnicodeDecodeError when the data from os.read does not end at a UTF-8 character boundary. For example, if only the first byte of a multi-byte UTF-8 character is returned by the end of the os.read, the full character cannot be decoded.

**Comment by benfrankel** [comment]
Note this was tested with Python 3.

**Comment by lantz** [comment]
Would you like to submit a PR?

**Comment by benfrankel** [comment]
Sure, WIP.

**Comment by benfrankel** [comment]
So this is a separate issue, but my PR's build seems to be failing for Python 3 because `pexpect.spawn( 'mn --link tc,bw=10,delay=10ms )` uses Python 2 (I might be wrong, but I see `u'...'` in the failed test's output which suggests a unicode string is being printed a la Python 2).
