### ISSUE TITLE
Mininet on Smartphones

### ISSUE THREAD

**Issue by LuisMiguelOG** [mininet/mininet#899]
Hello team,

I'm trying to use mininet in two Android devices using two apps: Userland (simulates the Ubuntu Kernel) and xServerXDSL (as graphic server. But is not strictly necessary).
I have been testing in two devices: Nexus 5 and Samsung s8 with Ubuntu and Fedora in both enviroments.
The steps I follow are always the same:
1) sudo apt update
2) sudo apt install git
3) git clone git://github.com/mininet/mininet
4) mininet/util/install.sh -a
5) sudo mn --test pingall

The current enviroment is:
**Nexus 5**
- ARMv7 Processor rev 0 (v7l)
$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.3 LTS
Release: 18.04
Codename: bionic
**Samsung s8**
- Aarch 64 GNU/Linux
$lsb_release -a 
"Same as above"

On both devices the problme is that mininet never starts.

When run the command: **$sudo mn --test pingall**
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** Adding hosts:
... (here is where it get stuck).

I'm really newbie with all this stuff and maybe I'm missing something. Or the problem is trying to use mininet on the smartphone. If I use other functionality like Miniedit works perfect, but if I try to run the topo created I get the same issue.

Kind Regards.

**Comment by lantz** [comment]
Can you confirm that network namespaces work properly in your environment?

In particular, `sudo mnexec -h bash` should start up a `bash` process in a network namespace; if you use `ip a` or `ifconfig -a` you should see a single network interface, the loopback interface.

**Comment by LuisMiguelOG** [comment]
Hello lantz,

Sorry for my late response, I've been pretty busy with other project.

Seems that network namesspaces work correctly.

The command `$ip a` display many interfaces, but the first one is the loopback interface.

**Comment by lantz** [comment]
Sorry, minor typo. Should have been `sudo mnexec -n` not `-h`.

Can you confirm that `sudo mnexec -n ip a` only shows the loopback interface? 

```
$ sudo mnexec -n ip a
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
```

If you see other interfaces, then network namespaces are **not** working properly and mininet will not be able to function.

**Comment by LuisMiguelOG** [comment]
Thanks for your prompt reply.

You're probably rigth.

With the command: `$ sudo mnexec -n ip -a` I get the message:

> unshare: Operation not permitted

![Cap](https://user-images.githubusercontent.com/49723467/72099745-89611600-3321-11ea-8d2c-f934b272d46b.PNG)

**Comment by cheriimoya** [comment]
The kernel has to support networking namespaces, i think userland and other android apps simply spawn containers that share the hosts kernel with mininet.
If the android host kernel doesn't support network namespaces, you cannot run mininet on this device.

It might work to spawn a full vm inside your android device, this should work then.

I guess this can therefore be closed.

**Comment by lantz** [comment]
Unfortunately this won't work until android properly enables network namespaces.

Ubuntu for Windows has a similar issue where netns support doesn't work as expected, I believe because of they way they integrate bridging with the Windows network devices.

Closing because it's an OS issue rather than a Mininet issue.

**Comment by lantz** [comment]
However, it might be possible to run mininet in the browser under jslinux.

**Comment by lantz** [comment]
Looks like Android 13 supports a VMM that can run ARM Win11, so perhaps it can run ARM Ubuntu 20.
