### ISSUE TITLE
Include net-tools as a installation package in install.sh

### ISSUE THREAD

**Issue by diveshuttam** [mininet/mininet#900]
Mininet uses GitHub issues for bug reports and feature requests only.
These issues can be viewed at bugs.mininet.org

If you have a question that is not a bug report or a feature request,
please use the documentation at docs.mininet.org, the FAQ
at faq.mininet.org, and the mininet-discuss mailing list.

For bug reports, please fill in the following information in detail,
and also feel free to include additional information such as debug
output from mn -v debug, etc.

### System Configuration
 - Ubuntu 18.04 **minimal install** in virtual-box
 - mininet 2.2.2

After installing mininet through install.sh, the following error comes up on the shell:

```
$ sudo mn
*** Creating network*** 
Adding controller
Cannot find required executable ifconfig.
Please make sure that Mininet is installed and available in your $PATH:(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin)
```
Installing net-tools (which has ifconfig binary) solves the problem. 
I believe mininet install.sh should install net-tools too.

**Comment by cheriimoya** [comment]
this is actually fixed, see https://github.com/mininet/mininet/blob/8a50d3867c49781c60b6171acc6e4b46954b4281/util/install.sh#L184

can be closed
