### ISSUE TITLE
addNode should return the Node object instead of the name

### ISSUE THREAD

**Issue by teto** [mininet/mininet#905]
### Expected/Desired Behavior:
I would like addNode to return the Node object instead of the name.
```
    def addNode( self, name, **opts ):
        """Add Node to graph.
           name: name
           opts: node options
           returns: node name"""
        self.g.add_node( name, **opts )
        return name
```
It's kinda strange to return a name I passed, also when I could retreive the name from the object itself.
I have some custom nodes with different members I would like to initialize so being able to do
```
h = addHost("host1")
h.init_bpf()
h.init_mptcp()
h.run_diagnostic()
```
would be easier for me.

**Comment by lantz** [comment]
You seem to be  confusing topology templates (`Topo`) with instantiated networks (`Mininet`). `Topo.addNode` does return the node, which is a string.

`Mininet.addHost()` does in fact return the `Host` object. This is the 'mid-level' API described in  the Introduction to Mininet document.

**Comment by lantz** [comment]
Closing as this seems to be covered in the documentation.
