### ISSUE TITLE
Generating SSL traffic between hosts 

### ISSUE THREAD

**Issue by KAMRANMEHBOOB** [mininet/mininet#908]
Hi.
I wanted to generate a SSL/TLS handshake between two hosts H1 H2 inside the mininet. 
After setting one of the hosts as the server(iperf -s) and the other one as the client(iperf -c ipaddr)
i wanted a ssl handshake to happen between them. In wire-shark i only see tcp messages being exchanged between them.
Is it possible in mininet? 
Regards,
Kamran

**Comment by lantz** [comment]
Please do not abuse the github issue system, thanks!
