### ISSUE TITLE
Wireshark GUI unusable

### ISSUE THREAD

**Issue by zjiekai** [mininet/mininet#909]
### Actual Behavior:
The wireshark GUI is not working.  Mouse clicks are not working. Scrolling to select interface is not working.

### Additional Information:
Ubuntu 18.04.3 with virtualbox
mininet-2.2.2-170321-ubuntu-14.04.4-server-amd64

![Screenshot from 2019-11-09 23-14-18](https://user-images.githubusercontent.com/1871071/68530793-af306580-0346-11ea-9e8b-5bf31a685a7b.png)

**Comment by zjiekai** [comment]
Installed mininet in an ubuntu 18.04 vm, x11 wireshark GUI works now.

**Comment by ubi23** [comment]
@zjiekai how were you able to fix it? I've been having this issue for more than a month now.

**Comment by lantz** [comment]
Unfortunately Qt isn't compatible with X11 on macOS.

I think the fix is to have `install.sh` install the GNOME version of wireshark, which works fine running against older x.org implementations.

**Comment by zjiekai** [comment]
@ubi23 I installed mininet manually without the official vm

**Comment by lantz** [comment]
OK, I will assume that there is not an issue with the current Mininet installation in 18.04.

**Comment by IamBushra** [comment]
I have the same issue, May you explain how I can install Wireshark-gtk in Mininet-VM? Thanks

**Comment by IamBushra** [comment]
when I try to install Wireshark-gtk have this error
```
mininet@mininet-vm:~/mininet$ sudo apt-get install wireshark-gtk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package wireshark-gtk

```

**Comment by escrowdis** [comment]
Hi, I have a similar issue that GUI is responsive when there will be a new window pop out by a mouse click, but not responsive with a mouse click on the same window. For example, I click "Capture Options" and the window pop out. There's no response when I try to scroll the bar or click the Capture checkbox, like 'eth0'. But if you close the "Capture Options" window and open it again, you can see the eth0 is clicked. It somehow failed to update the GUI. Any suggestion is appreciated. Thanks!
