### ISSUE TITLE
 could not find the source code file of openvswitch

### ISSUE THREAD

**Issue by jibanli** [mininet/mininet#914]
I followed the step Option 2: Native Installation from Source in http://mininet.org/download/
The os version is ubuntu 18.04 .

![mn_ovs](https://user-images.githubusercontent.com/39478794/69839484-ad492a80-1292-11ea-939c-da4fcc688fd3.png)
I used the command whereis openvswitch but could not find its source file.

**Comment by cheriimoya** [comment]
what do you mean by source file?
the install.sh script downloads the tarball of openvswitch (source code) and compiles it.
the compiled result will then be installed...
if you used the installation script, you can probably find the source code of openvswitch in your home directory (or the same directory that the mininet repository is located ad)

**Comment by lantz** [comment]
Closing since this seems to be a question rather than a bug and @cheriimoya  probably answered it.
