### ISSUE TITLE
Wiki page for the VM download is empty

### ISSUE THREAD

**Issue by Garen7** [mininet/mininet#915]
### Expected/Desired Behavior:
After clicking the download link there will be a download
### Actual Behavior:
https://github.com/mininet/mininet/wiki/Mininet-VM-Images
![image](https://user-images.githubusercontent.com/22408776/69897104-9f37f000-130c-11ea-9fb4-2f5958e3ed25.png)

### Detailed Steps to Reproduce the Behavior:
1. Go to http://mininet.org/download/
2. Click on 'Download the Mininet VM image.'
### Additional Information:
It looks like 2 commits 2 days ago broke it, the commit before those two works just fine
![image](https://user-images.githubusercontent.com/22408776/69897135-f50c9800-130c-11ea-99f7-a7647f08bbb1.png)

**Comment by cheriimoya** [comment]
this is fixed @lantz

**Comment by lantz** [comment]
Probably this should be moved to static pages to avoid vandalism.
