### ISSUE TITLE
Link on Mininet Apps and Tools is malware site

### ISSUE THREAD

**Issue by garymazz** [mininet/mininet#922]
The **http://www.ramonfontes.com/vnd** link on **https://github.com/mininet/mininet/wiki/Mininet-Apps-and-Tools** is a malware site.

`Visual Network Description - VND (http://www.ramonfontes.com/vnd) - A GUI tool that allows automatic creation of Mininet and Openflow Controllers Scripts."
`

**Comment by lantz** [comment]
That's surprising. Would you like to fix the link?

**Comment by lantz** [comment]
@ramonfontes do you know anything about this?

**Comment by ramonfontes** [comment]
Hi @lantz! Well, I don't have that domain anymore but I don't think it's a malware. However, you can consider  github.com/ramonfontes/vnd @garymazz. Also, I suggest you to use Miniedit https://github.com/mininet/mininet/tree/master/examples.  If you are interested to work with wireless nodes, you may want to consider the Mininet-WiFi version too https://github.com/intrig-unicamp/mininet-wifi/tree/master/examples. You can find a brief demo of the WiFi version at https://www.youtube.com/watch?v=j4JS4xxCrCA

**Comment by ramonfontes** [comment]
I just fixed the URL at [https://github.com/mininet/mininet/wiki/Mininet-Apps-and-Tools](https://github.com/mininet/mininet/wiki/Mininet-Apps-and-Tools)

**Comment by garymazz** [comment]
@lantz,  @ramonfontes , 

Sorry, I just got back in.. Thanks for fixing the page.  

@ramonfontes  I'm playing with some mesh simulators in OpenWrt running in VMware and Kubernetes.  I thought a little gui would help me. I'd like place it in a k3 container inside of OpenWrt.

cheers

**Comment by nazeehH** [comment]
hello
can you help me to install vlc on mininet machine?

**Comment by eknoes** [comment]
> I just fixed the URL at https://github.com/mininet/mininet/wiki/Mininet-Apps-and-Tools

There is still the following entry, which url redirects me to some scamware site:

> Visual Network Description - VND (http://www.ramonfontes.com/vnd) - A GUI tool that allows automatic creation of Mininet and Openflow Controllers Scripts.

**Comment by ramonfontes** [comment]
Fixed!

**Comment by cheriimoya** [comment]
so can this be closed @ramonfontes ?

**Comment by ramonfontes** [comment]
Yes, for sure.
