### ISSUE TITLE
install.sh fails; No cgroup-bin installation candidate (Ubuntu 19.10)

### ISSUE THREAD

**Issue by mikeperalta1** [mininet/mininet#940]
### Expected/Desired Behavior:
Able to install mininet from source, either tag 2.2.2 or master.

### Actual Behavior:
Unable to install mininet from source, tag 2.2.2 nor master.

### Detailed Steps to Reproduce the Behavior:

- First cloned this repo
- Next, navigated to the repo directory and made sure master branch was checked out
- Next, executed ```util/install.sh -a```

Received the following output:
```bash
Installing Mininet dependencies
Reading package lists...
Building dependency tree...
Reading state information...
Package cgroup-bin is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  cgroup-tools:i386 cgroup-tools

E: Package 'cgroup-bin' has no installation candidate
```

### Additional Information:

Master branch was at: fa9fd770cafc087b918945cf10208efa7477ea99

uname:
```Linux msike 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

/etc/lsb-release:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"
```

Also tried various tags, including 2.2.2

**Comment by JuFil** [comment]
Hi Mike,

I had the same issue, PR #928 fixes this :)

Simply replace "cgroup-bin" by "cgroup-tools".

Best regards

**Comment by mikeperalta1** [comment]
> Hi Mike,
> 
> I had the same issue, PR #928 fixes this :)
> 
> Simply replace "cgroup-bin" by "cgroup-tools".
> 
> Best regards

Very cool and thank you. I thought that was the problem but was too lazy to go into the source. I think I'll try your suggestion.

**Comment by lantz** [comment]
Would either of you like to submit a pull request?

**Comment by mikeperalta1** [comment]
Closing my issue because the related pull request was merged.
