### ISSUE TITLE
Installation Failure: git clone git://github.com/mininet/mininet  Failed

### ISSUE THREAD

**Issue by wintersnow212** [mininet/mininet#959]
**Mininet uses GitHub issues for bug reports and feature requests only.**
These issues can be viewed at bugs.mininet.org

If you have a question that is not a **bug report** or a **feature request**,
please use the documentation at docs.mininet.org, the FAQ
at faq.mininet.org, and the mininet-discuss mailing list.

For bug reports, please fill in the following information in detail,
and also feel free to include additional information such as debug
output from mn -v debug, etc.
--- Cut Here ---
### Expected/Desired Behavior:
git clone successfully
### Actual Behavior:
git clone git://github.com/mininet/mininet
Cloning into 'mininet'...
fatal: read error: Connection reset by peer
### Detailed Steps to Reproduce the Behavior:
I tried it on a virtual box provided by coursera SDN course https://github.com/noise-lab/Coursera-SDN

**Comment by SPYFF** [comment]
This is not a mininet related issue. Try cloning with the following command:

```
git clone https://github.com/mininet/mininet.git
```

**Comment by cheriimoya** [comment]
can be closed @lantz
