### ISSUE TITLE
Mininet cannot connect to the POX controller in "Simple Router" lab assignment

### ISSUE THREAD

**Issue by Horacehxw** [mininet/mininet#969]
I am trying to go through mininet's [Simple Router Assignment](https://github.com/mininet/mininet/wiki/Simple-Router). I use a clean Ubuntu 20.04 virtual machine to set up environment step by step following [the setup guide](https://github.com/mininet/mininet/wiki/Environment-Setup). And then I try to test the connectivity of emulated topology. However Mininet is unable to connect to the POX controller.

### Expected/Desired Behavior:

According to the guide, the POX terminal should output  the following when Mininet is connected:

```
INFO:openflow.of_01:[Con 1/249473472573510] Connected to e2-e5-11-b6-b0-46
DEBUG:.home.ubuntu.cs144_lab3.pox_module.cs144.ofhandler:Connection [Con 1/249473472573510]
DEBUG:.home.ubuntu.cs144_lab3.pox_module.cs144.srhandler:SRServerListener catch RouterInfo even, info={'eth3': ('10.0.1.1', '86:05:70:7e:eb:56', '10Gbps', 3), 'eth2': ('172.64.3.1', 'b2:9e:54:d8:9d:cd', '10Gbps', 2), 'eth1': ('192.168.2.1', '36:61:7c:4f:b6:7b', '10Gbps', 1)}, rtable=[]
```

### Actual Behavior:

However, **the Mininet seems never connect to POX**. 

And if I start the sr_solution application, the POX terminal shows following output:

```
INFO:root:Client has connected to the LTProtocol server (1 update connections now live)
DEBUG:.home.horacehxw.Project.cs144_lab3.pox_module.cs144.srhandler:Accepted client at 127.0.0.1
DEBUG:.home.horacehxw.Project.cs144_lab3.pox_module.cs144.srhandler:recv VNS msg: AUTH_REPLY:  username=horacehxw
DEBUG:.home.horacehxw.Project.cs144_lab3.pox_module.cs144.srhandler:recv VNS msg: OPEN: topo_id=0 host=vrhost user=horacehxw
DEBUG:.home.horacehxw.Project.cs144_lab3.pox_module.cs144.srhandler:open-msg: 0, vrhost
DEBUG:.home.horacehxw.Project.cs144_lab3.pox_module.cs144.srhandler:interfaces not populated yet
```

And if I exit mininet and restart again, the POX terminal will continue output following message:

```
INFO:openflow.of_01:[Con 1/None] closing connection
WARNING:openflow.of_01:Bad OpenFlow version (6) on connection [Con 2/None]
INFO:openflow.of_01:[Con 2/None] closing connection
WARNING:openflow.of_01:Bad OpenFlow version (6) on connection [Con 3/None]
INFO:openflow.of_01:[Con 3/None] closing connection
WARNING:openflow.of_01:Bad OpenFlow version (6) on connection [Con 4/None]
INFO:openflow.of_01:[Con 4/None] closing connection
... ... ...
```

I think maybe there's version issue between Mininet, POX, and OpenFlow.

### Detailed Steps to Reproduce the Behavior:

Using the clean Ubuntu 20.04 virtual machine.

#### Set Up Environment

```bash
sudo apt-get update
sudo apt-get install -y git vim-nox python-setuptools python-all-dev flex bison traceroute

cd ~
git clone git://github.com/mininet/mininet
cd mininet
./util/install.sh -fnv

cd ~
git clone http://github.com/noxrepo/pox
cd pox
git checkout f95dd1a81584d716823bbf565fa68254416af603

cd ~
git clone git://github.com/dound/ltprotocol.git
cd ltprotocol 
sudo python setup.py install

cd ~
git clone https://huangty@bitbucket.org/huangty/cs144_lab3.git
cd cs144_lab3/
git checkout --track remotes/origin/standalone

cd ~/cs144_lab3
./config.sh
```

#### Test Connectivity

In one terminal, start Mininet emulation:

```bash
cd ~/cs144_lab3/
./run_mininet.sh
```

In another terminal, start POX controller:

```bash
cd ~/cs144_lab3/
ln -s ../pox
./run_pox.sh
```

**Comment by Horacehxw** [comment]
Besides, there's no available AMI Image in Amazon "Oregon" region...

**Comment by shane-zhang** [comment]
Hi, this is caused by the incompatibility of the OpenFlow version. As shown in 
https://github.com/noxrepo/pox/blob/gar-experimental/pox/openflow/libopenflow_01.py#L4454
This can be solved by forcing the mininet controller(switch) to use OpenFlow1.0 by changing 
https://bitbucket.org/huangty/cs144_lab3/src/4958006832a136f0cff61c86dcb8ee9d008e234d/lab3.py#lines-31
to
`router = self.addSwitch( 'sw0' , protocols = ["OpenFlow10"])`
