### ISSUE TITLE
Broken links for demo code on wiki

### ISSUE THREAD

**Issue by mjforanVT** [mininet/mininet#975]
Sorry if this is the wrong place for this!

I am trying to run the [DHCP Masquerade example](https://github.com/mininet/mininet/wiki/Dhcp-masquerade-attack) but all of the bitbucket links belonging to @lantz are broken. For example, there is supposed to be a git repository for the demo code at [https://bitbucket.org/lantz/cs144-dhcp](https://bitbucket.org/lantz/cs144-dhcp) but it gives a 404 error. Same for the video demo at the bottom of the page. This code is required to run the demo! Should be an easy fix so I hope this can be resolved soon.

**Comment by lantz** [comment]
Strange but should be fixed now I think. If not, feel free to reopen this issue.
