### ISSUE TITLE
Ubuntu Package Installation fails "mn --test pingall"

### ISSUE THREAD

**Issue by ModestMC** [mininet/mininet#978]
# Expected/Desired Behavior:
I'm assuming this is like the hello world for mininet, not really sure what it should do but I assume it should just work

### Actual Behavior:
It calls /usr/bin/mn, then when it goes to run line 120 fails with the following error:

File "/usr/bin/mn", line 120
    print "%s" % VERSION
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean                                                                                                                            print("%s" % VERSION)?

I'm assuming this got patched elsewhere or just is a python versioning issue. The box is a clean install of Ubuntu18.04

### Detailed Steps to Reproduce the Behavior:
sudo apt-get install -y mininet
sudo mn --test pingall

### Additional Information:

I believe the syntax for this used in python2 would be ok but in python 3 fails. Default python on the machine is version 3.6.9. I'm going to try adding the parenthesis and seeing if it runs.

**Comment by ModestMC** [comment]
It promptly failed on a different line, does anyone know what version of python it's supposed to be using here?

**Comment by ModestMC** [comment]
I modified that line as well and now it says "no module named mininet". I'm going to try removing this thing and just installing from source.

**Comment by jeffallen** [comment]
Installing from source (see PR #980 for fixes needed) will solve this, because mininet has been upgraded for Python 3, but there's no released version since then.

**Comment by cheriimoya** [comment]
should work now tho, can probably be closed
