### ISSUE TITLE
mn --custom doesn't work when using python f-strings for node names

### ISSUE THREAD

**Issue by nicksettoon** [mininet/mininet#981]
output from mn -v debug, etc.
--- Cut Here ---
### Expected/Desired Behavior:
topography is loaded and network is started

### Actual Behavior:
Output:
Caught exception. Cleaning up...

SyntaxError: invalid syntax (topo.py, line 11)
drops back to shell prompt after this.

### Detailed Steps to Reproduce the Behavior:

create node in topology build() and use f-string for formatting its name
aswitch = self.addSwitch(f"l{currlvl}s{count}")

the following works perfectly fine:
aswitch = self.addSwitch("l{}s{}".format(currlvl, count)

### Additional Information:
command used to create custom topology
topo.py has topos = {"prod":Prod} where Prod(Topo) is the class definition

$sudo mn -v debug --custom topo.py --topo=prod

**Comment by lantz** [comment]
This is correct behavior in Python 2.
Can you confirm you are executing Mininet with Python 3?

```
$ sudo python2 `which mn` -v output
mininet> px from sys import version_info; print(version_info)
sys.version_info(major=2, minor=7, micro=18, releaselevel='final', serial=0)
mininet> 
openflow@ubuntu20:~$ sudo python3 `which mn` -v output
mininet> px from sys import version_info; print(version_info)
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

**Comment by nicksettoon** [comment]
> This is correct behavior for Python 2.
> 
> 1. Can you confirm you are executing Mininet with Python 3?
> 
> ```
> $ sudo mn -v output
> mininet> px from sys import version_info; print(version_info)
> sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
> ```
> 
> 2. Can you also confirm that the same behavior happens when you explicitly run `mn` using `python3`?
>    ```
>     sudo python3 `which mn` -v debug --custom topo.py --topo=prod
>    ```

yeah. finished the assignment and completely forgot about this sorry.
I've no way of testing this any time soon.
