### ISSUE TITLE
How to enable ssh login between mininet hosts

### ISSUE THREAD

**Issue by drobinkent** [mininet/mininet#982]
I have created a topology using mininet. It have 16 hosts (h1-h16). Now I want to run a python script from h1. This will will login to each server and run some commands.

But I am unable to ssh login to a host from another host. I have setup the "HostbasedAuthentication no: in the sshd_config, But still it's not working.

Can someone help to understand the procedure in detail?

If you have a question that is not a **bug report** or a **feature request**,
please use the documentation at docs.mininet.org, the FAQ
at faq.mininet.org, and the mininet-discuss mailing list.

For bug reports, please fill in the following information in detail,
and also feel free to include additional information such as debug
output from mn -v debug, etc.

**Comment by lantz** [comment]
Please do not ignore the github issue template, which clearly states that issues are not a q&a system.
Feel free to write to `mininet-discuss` or to check the ssh example in `examples/`

**Comment by lantz** [comment]
Closing, please read my comment above.

**Comment by lmaycotte** [comment]
I use paramiko for ssh'ing trough Python,


   1. host = "test.rebex.net"
   2. port = 22.
   3. username = "demo"
   4. password = "password"
   5. command = "ls"
   6. *ssh* = paramiko. SSHClient()
   7. *ssh*. set_missing_host_key_policy(paramiko. AutoAddPolicy())
   8. *ssh*. connect(host, port, username, password)
